C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_cost_modval_tl( modval, modval_tl, num_file, ri, rj, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use arr_mod, only : arr,narrival,nmaxarr
      use arr_mod, only : arr_tl
      use srpos_mod, only : pos
      use ihop_mod, only : rad2deg

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nr = 100
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: nts = 1080
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 32
      integer, parameter :: sny = 37

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      double precision :: ahybsigmc(nr)
      double precision :: ahybsigmf(nr+1)
      double precision :: anglecosc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: anglesinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: bhybsigmc(nr)
      double precision :: bhybsigmf(nr+1)
      double precision :: dahybsigc(nr+1)
      double precision :: dahybsigf(nr)
      double precision :: dbhybsigc(nr+1)
      double precision :: dbhybsigf(nr)
      double precision :: drc(nr+1)
      double precision :: drf(nr)
      double precision :: dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcori(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcoricos(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcorig(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskins(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskinw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: masks(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rc(nr)
      double precision :: recip_drc(nr+1)
      double precision :: recip_drf(nr)
      double precision :: recip_dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rf(nr+1)
      double precision :: rlows(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rloww(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ro_surf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfs(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: u2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: v2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_rs/ dxc, dxf, dxg, dxv, dyc, dyf, dyg, dyu, rloww, rlows, ro_surf, rsurfw, rsurfs, recip_dxc, recip_dxf, 
     $recip_dxg, recip_dxv, recip_dyc, recip_dyf, recip_dyg, recip_dyu, xc, yc, ra, raw, ras, raz, xg, yg, maskinc, maskinw, 
     $maskins, maskc, maskw, masks, recip_ra, recip_raw, recip_ras, recip_raz, drc, drf, recip_drc, recip_drf, rc, rf, ahybsigmf, 
     $bhybsigmf, ahybsigmc, bhybsigmc, dahybsigf, dbhybsigf, dbhybsigc, dahybsigc, tanphiatu, tanphiatv, anglecosc, anglesinc, 
     $u2zondir, v2zondir, fcori, fcorig, fcoricos

      double precision :: hfacc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: hfacs(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: hfacw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: r_low(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_hfacc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_hfacs(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_hfacw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_rcol(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_var_rs/ hfacc, hfacw, hfacs, recip_hfacc, recip_hfacw, recip_hfacs, r_low, recip_rcol

      integer :: ihop_iter(nts)
      integer :: ihop_nalpha
      integer :: ihop_npts_idw
      integer :: ihop_npts_range
      integer :: ihop_nrd
      integer :: ihop_nrr
      integer :: ihop_nsd
      integer :: ihop_nts
      common /ihop_params_i/ ihop_nts, ihop_nsd, ihop_nrd, ihop_nrr, ihop_npts_range, ihop_npts_idw, ihop_nalpha, ihop_iter

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      double precision :: ihop_ssp_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d_tl/ ihop_ssp_tl

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

C==============================================
C declare arguments
C==============================================
      double precision, intent(inout) :: modval
      double precision, intent(out) :: modval_tl
      double precision, intent(in) :: myiter
      integer, intent(in) :: mythid
      integer :: num_file
      integer :: ri
      integer :: rj

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      integer :: i
      integer :: ig
      integer :: ithi
      integer :: itlo
      integer :: j
      integer :: jg
      integer :: jthi
      integer :: jtlo
      integer :: k
      double precision :: locqoi
      double precision :: locqoi_tiled(nsx,nsy)
      double precision :: locqoi_tiled_tl(nsx,nsy)
      double precision :: locqoi_tl
      double precision :: locvol
      integer :: t

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      jtlo = mybylo(mythid)
      jthi = mybyhi(mythid)
      itlo = mybxlo(mythid)
      ithi = mybxhi(mythid)
      do t = 1, nts
        if (ihop_iter(t) >= 0 .and. myiter == ihop_iter(t)) then
          locvol = 0.
          do bj = jtlo, jthi
            do bi = itlo, ithi
              locqoi_tiled_tl(bi,bj) = 0.d0
              locqoi_tiled(bi,bj) = 0.
            end do
          end do
          locqoi_tl = 0.d0
          locqoi = 0.
          do bj = jtlo, jthi
            do bi = itlo, ithi
              do k = 1, 85
                do j = 1, sny
                  jg = myygloballo-1+(bj-1)*sny+j
                  do i = 1, snx
                    ig = myxgloballo-1+(bi-1)*snx+i
                    if (jg >= 44 .and. jg <= 52 .and. ig >= 12 .and. ig <= 16) then
      locvol = locvol+ra(i,j,bi,bj)*drf(k)*hfacc(i,j,k,bi,bj)
      locqoi_tiled_tl(bi,bj) = ihop_ssp_tl(i,j,k,bi,bj)+locqoi_tiled_tl(bi,bj)
      locqoi_tiled(bi,bj) = locqoi_tiled(bi,bj)+ihop_ssp(i,j,k,bi,bj)
                    endif
                  end do
                end do
              end do
              write(unit=standardmessageunit,fmt='(A,E22.17)') 'ESCOBAR V*dt*QoI(t) tiled: ',locqoi_tiled(bi,bj)
            end do
          end do
          if (locqoi_tiled(1,1) /= 0) then
            call global_sum_tile_rl( locqoi_tiled_tl,locqoi_tl,mythid )
            call global_sum_tile_rl( locqoi_tiled,locqoi,mythid )
            locqoi_tl = locqoi_tl*(1/locvol/deltat)
            locqoi = locqoi/locvol/deltat
          endif
          modval_tl = locqoi_tl
          modval = locqoi
        else
          modval_tl = 0.d0
          modval = 0
        endif
      end do
      write(unit=standardmessageunit,fmt='(A,E22.17)') 'ESCOBAR modVal',modval
      write(unit=standardmessageunit,fmt='(A,E22.17)') 'ESCOBAR modVal_tl',modval_tl

      end subroutine ihop_cost_modval_tl

      subroutine ihop_cost_modval( modval, num_file, ri, rj, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use arr_mod, only : arr,narrival,nmaxarr
      use srpos_mod, only : pos
      use ihop_mod, only : rad2deg

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nr = 100
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: nts = 1080
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 32
      integer, parameter :: sny = 37

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      double precision :: ahybsigmc(nr)
      double precision :: ahybsigmf(nr+1)
      double precision :: anglecosc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: anglesinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: bhybsigmc(nr)
      double precision :: bhybsigmf(nr+1)
      double precision :: dahybsigc(nr+1)
      double precision :: dahybsigf(nr)
      double precision :: dbhybsigc(nr+1)
      double precision :: dbhybsigf(nr)
      double precision :: drc(nr+1)
      double precision :: drf(nr)
      double precision :: dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcori(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcoricos(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcorig(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskins(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskinw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: masks(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rc(nr)
      double precision :: recip_drc(nr+1)
      double precision :: recip_drf(nr)
      double precision :: recip_dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rf(nr+1)
      double precision :: rlows(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rloww(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ro_surf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfs(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: u2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: v2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_rs/ dxc, dxf, dxg, dxv, dyc, dyf, dyg, dyu, rloww, rlows, ro_surf, rsurfw, rsurfs, recip_dxc, recip_dxf, 
     $recip_dxg, recip_dxv, recip_dyc, recip_dyf, recip_dyg, recip_dyu, xc, yc, ra, raw, ras, raz, xg, yg, maskinc, maskinw, 
     $maskins, maskc, maskw, masks, recip_ra, recip_raw, recip_ras, recip_raz, drc, drf, recip_drc, recip_drf, rc, rf, ahybsigmf, 
     $bhybsigmf, ahybsigmc, bhybsigmc, dahybsigf, dbhybsigf, dbhybsigc, dahybsigc, tanphiatu, tanphiatv, anglecosc, anglesinc, 
     $u2zondir, v2zondir, fcori, fcorig, fcoricos

      double precision :: hfacc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: hfacs(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: hfacw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: r_low(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_hfacc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_hfacs(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_hfacw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: recip_rcol(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_var_rs/ hfacc, hfacw, hfacs, recip_hfacc, recip_hfacw, recip_hfacs, r_low, recip_rcol

      integer :: ihop_iter(nts)
      integer :: ihop_nalpha
      integer :: ihop_npts_idw
      integer :: ihop_npts_range
      integer :: ihop_nrd
      integer :: ihop_nrr
      integer :: ihop_nsd
      integer :: ihop_nts
      common /ihop_params_i/ ihop_nts, ihop_nsd, ihop_nrd, ihop_nrr, ihop_npts_range, ihop_npts_idw, ihop_nalpha, ihop_iter

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

C==============================================
C declare arguments
C==============================================
      double precision :: modval
      double precision :: myiter
      integer :: mythid
      integer :: num_file
      integer :: ri
      integer :: rj

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      integer :: i
      integer :: ig
      integer :: ithi
      integer :: itlo
      integer :: j
      integer :: jg
      integer :: jthi
      integer :: jtlo
      integer :: k
      double precision :: locqoi
      double precision :: locqoi_tiled(nsx,nsy)
      double precision :: locvol
      integer :: t

      jtlo = mybylo(mythid)
      jthi = mybyhi(mythid)
      itlo = mybxlo(mythid)
      ithi = mybxhi(mythid)
      do t = 1, nts
        if (ihop_iter(t) >= 0 .and. myiter == ihop_iter(t)) then
          locvol = 0.
          do bj = jtlo, jthi
            do bi = itlo, ithi
              locqoi_tiled(bi,bj) = 0.
            end do
          end do
          locqoi = 0.
          do bj = jtlo, jthi
            do bi = itlo, ithi
              do k = 1, 85
                do j = 1, sny
                  jg = myygloballo-1+(bj-1)*sny+j
                  do i = 1, snx
                    ig = myxgloballo-1+(bi-1)*snx+i
                    if (jg >= 44 .and. jg <= 52 .and. ig >= 12 .and. ig <= 16) then
      locvol = locvol+ra(i,j,bi,bj)*drf(k)*hfacc(i,j,k,bi,bj)
      locqoi_tiled(bi,bj) = locqoi_tiled(bi,bj)+ihop_ssp(i,j,k,bi,bj)
                    endif
                  end do
                end do
              end do
              write(unit=standardmessageunit,fmt='(A,E22.17)') 'ESCOBAR V*dt*QoI(t) tiled: ',locqoi_tiled(bi,bj)
            end do
          end do
          if (locqoi_tiled(1,1) /= 0) then
            call global_sum_tile_rl( locqoi_tiled,locqoi,mythid )
            locqoi = locqoi/locvol/deltat
          endif
          modval = locqoi
        else
          modval = 0
        endif
      end do
      write(unit=standardmessageunit,fmt='(A,E22.17)') 'ESCOBAR modVal',modval
      end subroutine ihop_cost_modval
