C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine forward_step_tl( iloop, mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      double precision :: etan(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: gsnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gtnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gu(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gunm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gv(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gvnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: salt(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: theta(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: uvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: vvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: wvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /dynvars_r/ etan, uvel, vvel, wvel, theta, salt, gu, gv, gunm1, gvnm1, gtnm1, gsnm1

      logical :: debugmode
      logical :: eebooterror
      logical :: eeenderror
      logical :: fatalerror
      logical :: printmapincludeszeros
      logical :: usecoupler
      logical :: usecubedsphereexchange
      logical :: usenest2w_child
      logical :: usenest2w_parent
      logical :: usenest_child
      logical :: usenest_parent
      logical :: useoasis
      logical :: usesetrlstk
      logical :: usesigreg
      logical :: usesinglecpuinput
      logical :: usesinglecpuio
      common /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, 
     $usecubedsphereexchange, usecoupler, usenest_parent, usenest_child, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, 
     $usesigreg

      double precision :: etan_tl(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: gsnm1_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gtnm1_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gu_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gunm1_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gv_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gvnm1_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: salt_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: theta_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: uvel_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: vvel_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: wvel_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /g_dynvars_r/ etan_tl, uvel_tl, vvel_tl, wvel_tl, theta_tl, salt_tl, gu_tl, gv_tl, gunm1_tl, gvnm1_tl, gtnm1_tl, 
     $gsnm1_tl

      integer :: cg2dmaxiters
      integer :: cg2dminitersnsa
      integer :: cg2dprecondfreq
      integer :: cg2duseminressol
      integer :: cg3dmaxiters
      integer :: debuglevel
      integer :: momforcingoutab
      integer :: monitorselect
      integer :: nenditer
      integer :: niter0
      integer :: nonlinfreesurf
      integer :: ntimesteps
      integer :: ntimesteps_l2
      integer :: pcellmix_select
      integer :: plotlevel
      integer :: printresidualfreq
      integer :: readbinaryprec
      integer :: rwsuffixtype
      integer :: saltadvscheme
      integer :: saltvertadvscheme
      integer :: select3dcorischeme
      integer :: select_rstar
      integer :: selectaddfluid
      integer :: selectbalanceempmr
      integer :: selectbotdragquadr
      integer :: selectcorimap
      integer :: selectcorischeme
      integer :: selectimplicitdrag
      integer :: selectkescheme
      integer :: selectmetricterms
      integer :: selectnhfreesurf
      integer :: selectp_ineos_zc
      integer :: selectpenetratingsw
      integer :: selectsigmacoord
      integer :: selectvortscheme
      integer :: tempadvscheme
      integer :: tempvertadvscheme
      integer :: tracforcingoutab
      integer :: writebinaryprec
      common /parm_i/ cg2dmaxiters, cg2dminitersnsa, cg2dprecondfreq, cg2duseminressol, cg3dmaxiters, printresidualfreq, niter0, 
     $ntimesteps, ntimesteps_l2, nenditer, selectcorimap, selectsigmacoord, nonlinfreesurf, select_rstar, selectnhfreesurf, 
     $selectp_ineos_zc, selectaddfluid, selectbalanceempmr, selectimplicitdrag, momforcingoutab, tracforcingoutab, tempadvscheme, 
     $tempvertadvscheme, saltadvscheme, saltvertadvscheme, selectkescheme, selectvortscheme, selectmetricterms, selectcorischeme, 
     $select3dcorischeme, selectbotdragquadr, selectpenetratingsw, pcellmix_select, readbinaryprec, writebinaryprec, rwsuffixtype, 
     $monitorselect, debuglevel, plotlevel

      logical :: addfrictionheating
      logical :: allowfreezing
      logical :: applyexchuv_early
      logical :: balanceprintmean
      logical :: balanceqnet
      logical :: balancesaltclimrelax
      logical :: balancethetaclimrelax
      logical :: bottomvisc_pcell
      logical :: calc_wvelocity
      logical :: checkinisalt
      logical :: checkinitemp
      logical :: deepatmosphere
      logical :: doab_ongtgs
      logical :: doresethfactors
      logical :: dosaltclimrelax
      logical :: dothetaclimrelax
      logical :: dumpinitandlast
      logical :: exactconserv
      logical :: fluidisair
      logical :: fluidiswater
      logical :: globalfiles
      logical :: haswetcscorners
      logical :: highordervorticity
      logical :: implicitdiffusion
      logical :: implicitfreesurface
      logical :: implicitintgravwave
      logical :: implicitviscosity
      logical :: interdiffkr_pcell
      logical :: interviscar_pcell
      logical :: linfsconservetr
      logical :: maskinisalt
      logical :: maskinitemp
      logical :: momadvection
      logical :: momdissip_in_ab
      logical :: momforcing
      logical :: momimplvertadv
      logical :: mompressureforcing
      logical :: momstepping
      logical :: momtidalforcing
      logical :: momviscosity
      logical :: monitor_stdio
      logical :: multidimadvection
      logical :: no_slip_bottom
      logical :: no_slip_sides
      logical :: nonhydrostatic
      logical :: outputtypesinclusive
      logical :: periodicexternalforcing
      logical :: pickup_read_mdsio
      logical :: pickup_write_immed
      logical :: pickup_write_mdsio
      logical :: pickupstrictlymatch
      logical :: quasihydrostatic
      logical :: rigidlid
      logical :: rotategrid
      logical :: salt_staypositive
      logical :: saltadvection
      logical :: saltforcing
      logical :: saltimplvertadv
      logical :: saltisactivetr
      logical :: saltstepping
      logical :: saltvertdiff4
      logical :: setcenterdr
      logical :: setinterfdr
      logical :: snapshot_mdsio
      logical :: staggertimestep
      logical :: startfrompickupab2
      logical :: storephihyd4phys
      logical :: temp_staypositive
      logical :: tempadvection
      logical :: tempforcing
      logical :: tempimplvertadv
      logical :: tempisactivetr
      logical :: tempstepping
      logical :: tempvertdiff4
      logical :: timeave_mdsio
      logical :: uniformfreesurflev
      logical :: uniformlin_phisurf
      logical :: upwindshear
      logical :: upwindvorticity
      logical :: use3dsolver
      logical :: useabsvorticity
      logical :: useareavisclength
      logical :: usecdscheme
      logical :: usecoriolis
      logical :: usefullleith
      logical :: usejamartmomadv
      logical :: usemin4hfacedges
      logical :: usemultidimadvec
      logical :: usenhmterms
      logical :: usensacgsolver
      logical :: usepickupbeforec54
      logical :: userealfreshwaterflux
      logical :: usesmag3d
      logical :: usesrcgsolver
      logical :: usestraintensionvisc
      logical :: usingcartesiangrid
      logical :: usingcurvilineargrid
      logical :: usingcylindricalgrid
      logical :: usingpcoords
      logical :: usingsphericalpolargrid
      logical :: usingzcoords
      logical :: vectorinvariantmomentum
      logical :: writepickupatend
      common /parm_l/ fluidisair, fluidiswater, usingpcoords, usingzcoords, usingcartesiangrid, usingsphericalpolargrid, rotategrid,
     $ usingcylindricalgrid, usingcurvilineargrid, haswetcscorners, deepatmosphere, setinterfdr, setcenterdr, usemin4hfacedges, 
     $interviscar_pcell, interdiffkr_pcell, no_slip_sides, no_slip_bottom, bottomvisc_pcell, usesmag3d, usefullleith, 
     $usestraintensionvisc, useareavisclength, momviscosity, momadvection, momforcing, momtidalforcing, mompressureforcing, 
     $usenhmterms, usecoriolis, usecdscheme, vectorinvariantmomentum, usejamartmomadv, upwindvorticity, highordervorticity, 
     $useabsvorticity, upwindshear, momstepping, calc_wvelocity, tempstepping, saltstepping, addfrictionheating, temp_staypositive, 
     $salt_staypositive, tempadvection, tempvertdiff4, tempisactivetr, tempforcing, saltadvection, saltvertdiff4, saltisactivetr, 
     $saltforcing, maskinitemp, maskinisalt, checkinitemp, checkinisalt, usensacgsolver, usesrcgsolver, rigidlid, 
     $implicitfreesurface, uniformlin_phisurf, uniformfreesurflev, exactconserv, linfsconservetr, userealfreshwaterflux, 
     $storephihyd4phys, quasihydrostatic, nonhydrostatic, use3dsolver, implicitintgravwave, staggertimestep, applyexchuv_early, 
     $doresethfactors, implicitdiffusion, implicitviscosity, tempimplvertadv, saltimplvertadv, momimplvertadv, multidimadvection, 
     $usemultidimadvec, momdissip_in_ab, doab_ongtgs, balanceqnet, balanceprintmean, balancethetaclimrelax, balancesaltclimrelax, 
     $dothetaclimrelax, dosaltclimrelax, allowfreezing, periodicexternalforcing, globalfiles, pickupstrictlymatch, 
     $usepickupbeforec54, startfrompickupab2, pickup_read_mdsio, pickup_write_mdsio, pickup_write_immed, writepickupatend, 
     $timeave_mdsio, snapshot_mdsio, monitor_stdio, outputtypesinclusive, dumpinitandlast

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

      integer :: i_got_signal
      common /sig_i/ i_got_signal

C==============================================
C declare arguments
C==============================================
      integer, intent(in) :: iloop
      integer, intent(inout) :: myiter
      integer, intent(in) :: mythid
      double precision, intent(inout) :: mytime

C==============================================
C declare local variables
C==============================================
      logical :: modelend

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      if (debugmode) then
        call debug_enter( 'FORWARD_STEP',mythid )
      endif
      myiter = niter0+(iloop-1)
      mytime = starttime+deltatclock*(iloop-1)
      call g_autodiff_inadmode_unset( mytime,myiter,mythid )
      if (usediagnostics) then
        call diagnostics_switch_onoff( 1,mytime,myiter,mythid )
        call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        call do_statevars_diags( mytime,0,myiter,mythid )
        call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
      endif
      if (debugmode) then
        call debug_call( 'LOAD_FIELDS_DRIVER',mythid )
      endif
      call timer_start( 'LOAD_FIELDS_DRIVER  [FORWARD_STEP]',mythid )
      call load_fields_driver_tl( mytime,myiter,mythid )
      call timer_stop( 'LOAD_FIELDS_DRIVER  [FORWARD_STEP]',mythid )
      if (usectrl) then
        call timer_start( 'CTRL_MAP_FORCING  [FORWARD_STEP]',mythid )
        call ctrl_map_forcing_tl( mytime,myiter,mythid )
        call timer_stop( 'CTRL_MAP_FORCING  [FORWARD_STEP]',mythid )
      endif
      call g_dummy_in_stepping( mytime,myiter,mythid )
      if (debugmode) then
        call debug_call( 'DO_ATMOSPHERIC_PHYS',mythid )
      endif
      call timer_start( 'DO_ATMOSPHERIC_PHYS [FORWARD_STEP]',mythid )
      call do_atmospheric_phys( mytime,myiter,mythid )
      call timer_stop( 'DO_ATMOSPHERIC_PHYS [FORWARD_STEP]',mythid )
      if (debugmode) then
        call debug_call( 'DO_OCEANIC_PHYS',mythid )
      endif
      call timer_start( 'DO_OCEANIC_PHYS     [FORWARD_STEP]',mythid )
      call do_oceanic_phys_tl( mytime,myiter,mythid )
      call timer_stop( 'DO_OCEANIC_PHYS     [FORWARD_STEP]',mythid )
      if ( .not. staggertimestep) then
        if (debugmode) then
          call debug_call( 'THERMODYNAMICS',mythid )
        endif
        call timer_start( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
        call thermodynamics_tl( mytime,myiter,mythid )
        call timer_stop( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
      endif
      if (implicitintgravwave) then
        call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        call do_stagger_fields_exchanges_tl( mytime,myiter,mythid )
        call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      endif
      if (debugmode) then
        call debug_call( 'DYNAMICS',mythid )
      endif
      call timer_start( 'DYNAMICS            [FORWARD_STEP]',mythid )
      call dynamics_tl( mytime,myiter,mythid )
      call timer_stop( 'DYNAMICS            [FORWARD_STEP]',mythid )
      myiter = niter0+iloop
      mytime = starttime+deltatclock*iloop
      if (usemnc) then
        call mnc_update_time( mytime,myiter,mythid )
      endif
      if (momstepping) then
        call timer_start( 'SOLVE_FOR_PRESSURE  [FORWARD_STEP]',mythid )
        call solve_for_pressure_tl( mytime,myiter,mythid )
        call timer_stop( 'SOLVE_FOR_PRESSURE  [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'MOM_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call momentum_correction_step_tl( mytime,myiter,mythid )
      call timer_stop( 'MOM_CORRECTION_STEP [FORWARD_STEP]',mythid )
      if (calc_wvelocity) then
        call timer_start( 'INTEGR_CONTINUITY   [FORWARD_STEP]',mythid )
        call integr_continuity_tl( uvel,uvel_tl,vvel,vvel_tl,mytime,myiter,mythid )
        call timer_stop( 'INTEGR_CONTINUITY   [FORWARD_STEP]',mythid )
      endif
      if (staggertimestep) then
        if (debugmode) then
          call debug_call( 'DO_STAGGER_FIELDS_EXCH.',mythid )
        endif
        call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        call do_stagger_fields_exchanges_tl( mytime,myiter,mythid )
        call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        if (usediagnostics) then
          call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
          call do_statevars_diags( mytime,1,myiter,mythid )
          call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        endif
        if (debugmode) then
          call debug_call( 'THERMODYNAMICS',mythid )
        endif
        call timer_start( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
        call thermodynamics_tl( mytime,myiter,mythid )
        call timer_stop( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'TRC_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call tracers_correction_step_tl( mytime,myiter,mythid )
      call timer_stop( 'TRC_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      call do_fields_blocking_exchanges_tl( mythid )
      call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      if (useihop) then
        call ihop_sound_speed_tl( mythid )
        call timer_start( 'IHOP_DRIVER           [FORWARD_STEP]',mythid )
        call ihop_driver_tl( mytime,myiter,mythid )
        call timer_stop( 'IHOP_DRIVER           [FORWARD_STEP]',mythid )
      endif
      if (usediagnostics) then
        call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        call do_statevars_diags( mytime,2,myiter,mythid )
        call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
      endif
      if (monitorfreq > 0. .or. adjmonitorfreq > 0.) then
        call timer_start( 'MONITOR             [FORWARD_STEP]',mythid )
        call g_monitor( mytime,myiter,mythid )
        call timer_stop( 'MONITOR             [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'COST_TILE           [FORWARD_STEP]',mythid )
      call cost_tile( mytime,myiter,mythid )
      call timer_stop( 'COST_TILE           [FORWARD_STEP]',mythid )
      if (useecco) then
        call ecco_phys_tl( mytime,myiter,mythid )
      endif
      modelend = mytime == endtime .or. myiter == nenditer
      if (usesigreg) then
        modelend = modelend .or. i_got_signal > 0
      endif
      call timer_start( 'DO_THE_MODEL_IO     [FORWARD_STEP]',mythid )
      call do_the_model_io( modelend,mytime,myiter,mythid )
      call timer_stop( 'DO_THE_MODEL_IO     [FORWARD_STEP]',mythid )
      call timer_start( 'DO_WRITE_PICKUP     [FORWARD_STEP]',mythid )
      call do_write_pickup( modelend,mytime,myiter,mythid )
      call timer_stop( 'DO_WRITE_PICKUP     [FORWARD_STEP]',mythid )
      if (usesigreg) then
        if (modelend .and. i_got_signal > 0) then
          stop 'Checkpoint completed -- killed by signal handler'
        endif
      endif
      call g_autodiff_inadmode_set( mytime,myiter,mythid )
      if (debugmode) then
        call debug_leave( 'FORWARD_STEP',mythid )
      endif

      end subroutine forward_step_tl

      subroutine forward_step( iloop, mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      double precision :: etan(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: gsnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gtnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gu(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gunm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gv(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: gvnm1(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: salt(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: theta(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: uvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: vvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: wvel(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /dynvars_r/ etan, uvel, vvel, wvel, theta, salt, gu, gv, gunm1, gvnm1, gtnm1, gsnm1

      logical :: debugmode
      logical :: eebooterror
      logical :: eeenderror
      logical :: fatalerror
      logical :: printmapincludeszeros
      logical :: usecoupler
      logical :: usecubedsphereexchange
      logical :: usenest2w_child
      logical :: usenest2w_parent
      logical :: usenest_child
      logical :: usenest_parent
      logical :: useoasis
      logical :: usesetrlstk
      logical :: usesigreg
      logical :: usesinglecpuinput
      logical :: usesinglecpuio
      common /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, 
     $usecubedsphereexchange, usecoupler, usenest_parent, usenest_child, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, 
     $usesigreg

      integer :: cg2dmaxiters
      integer :: cg2dminitersnsa
      integer :: cg2dprecondfreq
      integer :: cg2duseminressol
      integer :: cg3dmaxiters
      integer :: debuglevel
      integer :: momforcingoutab
      integer :: monitorselect
      integer :: nenditer
      integer :: niter0
      integer :: nonlinfreesurf
      integer :: ntimesteps
      integer :: ntimesteps_l2
      integer :: pcellmix_select
      integer :: plotlevel
      integer :: printresidualfreq
      integer :: readbinaryprec
      integer :: rwsuffixtype
      integer :: saltadvscheme
      integer :: saltvertadvscheme
      integer :: select3dcorischeme
      integer :: select_rstar
      integer :: selectaddfluid
      integer :: selectbalanceempmr
      integer :: selectbotdragquadr
      integer :: selectcorimap
      integer :: selectcorischeme
      integer :: selectimplicitdrag
      integer :: selectkescheme
      integer :: selectmetricterms
      integer :: selectnhfreesurf
      integer :: selectp_ineos_zc
      integer :: selectpenetratingsw
      integer :: selectsigmacoord
      integer :: selectvortscheme
      integer :: tempadvscheme
      integer :: tempvertadvscheme
      integer :: tracforcingoutab
      integer :: writebinaryprec
      common /parm_i/ cg2dmaxiters, cg2dminitersnsa, cg2dprecondfreq, cg2duseminressol, cg3dmaxiters, printresidualfreq, niter0, 
     $ntimesteps, ntimesteps_l2, nenditer, selectcorimap, selectsigmacoord, nonlinfreesurf, select_rstar, selectnhfreesurf, 
     $selectp_ineos_zc, selectaddfluid, selectbalanceempmr, selectimplicitdrag, momforcingoutab, tracforcingoutab, tempadvscheme, 
     $tempvertadvscheme, saltadvscheme, saltvertadvscheme, selectkescheme, selectvortscheme, selectmetricterms, selectcorischeme, 
     $select3dcorischeme, selectbotdragquadr, selectpenetratingsw, pcellmix_select, readbinaryprec, writebinaryprec, rwsuffixtype, 
     $monitorselect, debuglevel, plotlevel

      logical :: addfrictionheating
      logical :: allowfreezing
      logical :: applyexchuv_early
      logical :: balanceprintmean
      logical :: balanceqnet
      logical :: balancesaltclimrelax
      logical :: balancethetaclimrelax
      logical :: bottomvisc_pcell
      logical :: calc_wvelocity
      logical :: checkinisalt
      logical :: checkinitemp
      logical :: deepatmosphere
      logical :: doab_ongtgs
      logical :: doresethfactors
      logical :: dosaltclimrelax
      logical :: dothetaclimrelax
      logical :: dumpinitandlast
      logical :: exactconserv
      logical :: fluidisair
      logical :: fluidiswater
      logical :: globalfiles
      logical :: haswetcscorners
      logical :: highordervorticity
      logical :: implicitdiffusion
      logical :: implicitfreesurface
      logical :: implicitintgravwave
      logical :: implicitviscosity
      logical :: interdiffkr_pcell
      logical :: interviscar_pcell
      logical :: linfsconservetr
      logical :: maskinisalt
      logical :: maskinitemp
      logical :: momadvection
      logical :: momdissip_in_ab
      logical :: momforcing
      logical :: momimplvertadv
      logical :: mompressureforcing
      logical :: momstepping
      logical :: momtidalforcing
      logical :: momviscosity
      logical :: monitor_stdio
      logical :: multidimadvection
      logical :: no_slip_bottom
      logical :: no_slip_sides
      logical :: nonhydrostatic
      logical :: outputtypesinclusive
      logical :: periodicexternalforcing
      logical :: pickup_read_mdsio
      logical :: pickup_write_immed
      logical :: pickup_write_mdsio
      logical :: pickupstrictlymatch
      logical :: quasihydrostatic
      logical :: rigidlid
      logical :: rotategrid
      logical :: salt_staypositive
      logical :: saltadvection
      logical :: saltforcing
      logical :: saltimplvertadv
      logical :: saltisactivetr
      logical :: saltstepping
      logical :: saltvertdiff4
      logical :: setcenterdr
      logical :: setinterfdr
      logical :: snapshot_mdsio
      logical :: staggertimestep
      logical :: startfrompickupab2
      logical :: storephihyd4phys
      logical :: temp_staypositive
      logical :: tempadvection
      logical :: tempforcing
      logical :: tempimplvertadv
      logical :: tempisactivetr
      logical :: tempstepping
      logical :: tempvertdiff4
      logical :: timeave_mdsio
      logical :: uniformfreesurflev
      logical :: uniformlin_phisurf
      logical :: upwindshear
      logical :: upwindvorticity
      logical :: use3dsolver
      logical :: useabsvorticity
      logical :: useareavisclength
      logical :: usecdscheme
      logical :: usecoriolis
      logical :: usefullleith
      logical :: usejamartmomadv
      logical :: usemin4hfacedges
      logical :: usemultidimadvec
      logical :: usenhmterms
      logical :: usensacgsolver
      logical :: usepickupbeforec54
      logical :: userealfreshwaterflux
      logical :: usesmag3d
      logical :: usesrcgsolver
      logical :: usestraintensionvisc
      logical :: usingcartesiangrid
      logical :: usingcurvilineargrid
      logical :: usingcylindricalgrid
      logical :: usingpcoords
      logical :: usingsphericalpolargrid
      logical :: usingzcoords
      logical :: vectorinvariantmomentum
      logical :: writepickupatend
      common /parm_l/ fluidisair, fluidiswater, usingpcoords, usingzcoords, usingcartesiangrid, usingsphericalpolargrid, rotategrid,
     $ usingcylindricalgrid, usingcurvilineargrid, haswetcscorners, deepatmosphere, setinterfdr, setcenterdr, usemin4hfacedges, 
     $interviscar_pcell, interdiffkr_pcell, no_slip_sides, no_slip_bottom, bottomvisc_pcell, usesmag3d, usefullleith, 
     $usestraintensionvisc, useareavisclength, momviscosity, momadvection, momforcing, momtidalforcing, mompressureforcing, 
     $usenhmterms, usecoriolis, usecdscheme, vectorinvariantmomentum, usejamartmomadv, upwindvorticity, highordervorticity, 
     $useabsvorticity, upwindshear, momstepping, calc_wvelocity, tempstepping, saltstepping, addfrictionheating, temp_staypositive, 
     $salt_staypositive, tempadvection, tempvertdiff4, tempisactivetr, tempforcing, saltadvection, saltvertdiff4, saltisactivetr, 
     $saltforcing, maskinitemp, maskinisalt, checkinitemp, checkinisalt, usensacgsolver, usesrcgsolver, rigidlid, 
     $implicitfreesurface, uniformlin_phisurf, uniformfreesurflev, exactconserv, linfsconservetr, userealfreshwaterflux, 
     $storephihyd4phys, quasihydrostatic, nonhydrostatic, use3dsolver, implicitintgravwave, staggertimestep, applyexchuv_early, 
     $doresethfactors, implicitdiffusion, implicitviscosity, tempimplvertadv, saltimplvertadv, momimplvertadv, multidimadvection, 
     $usemultidimadvec, momdissip_in_ab, doab_ongtgs, balanceqnet, balanceprintmean, balancethetaclimrelax, balancesaltclimrelax, 
     $dothetaclimrelax, dosaltclimrelax, allowfreezing, periodicexternalforcing, globalfiles, pickupstrictlymatch, 
     $usepickupbeforec54, startfrompickupab2, pickup_read_mdsio, pickup_write_mdsio, pickup_write_immed, writepickupatend, 
     $timeave_mdsio, snapshot_mdsio, monitor_stdio, outputtypesinclusive, dumpinitandlast

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

      integer :: i_got_signal
      common /sig_i/ i_got_signal

C==============================================
C declare arguments
C==============================================
      integer :: iloop
      integer :: myiter
      integer :: mythid
      double precision :: mytime

C==============================================
C declare local variables
C==============================================
      logical :: modelend

      if (debugmode) then
        call debug_enter( 'FORWARD_STEP',mythid )
      endif
      myiter = niter0+(iloop-1)
      mytime = starttime+deltatclock*(iloop-1)
      call autodiff_inadmode_unset( mytime,myiter,mythid )
      if (usediagnostics) then
        call diagnostics_switch_onoff( 1,mytime,myiter,mythid )
        call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        call do_statevars_diags( mytime,0,myiter,mythid )
        call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
      endif
      if (debugmode) then
        call debug_call( 'LOAD_FIELDS_DRIVER',mythid )
      endif
      call timer_start( 'LOAD_FIELDS_DRIVER  [FORWARD_STEP]',mythid )
      call load_fields_driver( mytime,myiter,mythid )
      call timer_stop( 'LOAD_FIELDS_DRIVER  [FORWARD_STEP]',mythid )
      if (usectrl) then
        call timer_start( 'CTRL_MAP_FORCING  [FORWARD_STEP]',mythid )
        call ctrl_map_forcing( mytime,myiter,mythid )
        call timer_stop( 'CTRL_MAP_FORCING  [FORWARD_STEP]',mythid )
      endif
      call dummy_in_stepping( mytime,myiter,mythid )
      if (debugmode) then
        call debug_call( 'DO_ATMOSPHERIC_PHYS',mythid )
      endif
      call timer_start( 'DO_ATMOSPHERIC_PHYS [FORWARD_STEP]',mythid )
      call do_atmospheric_phys( mytime,myiter,mythid )
      call timer_stop( 'DO_ATMOSPHERIC_PHYS [FORWARD_STEP]',mythid )
      if (debugmode) then
        call debug_call( 'DO_OCEANIC_PHYS',mythid )
      endif
      call timer_start( 'DO_OCEANIC_PHYS     [FORWARD_STEP]',mythid )
      call do_oceanic_phys( mytime,myiter,mythid )
      call timer_stop( 'DO_OCEANIC_PHYS     [FORWARD_STEP]',mythid )
      if ( .not. staggertimestep) then
        if (debugmode) then
          call debug_call( 'THERMODYNAMICS',mythid )
        endif
        call timer_start( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
        call thermodynamics( mytime,myiter,mythid )
        call timer_stop( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
      endif
      if (implicitintgravwave) then
        call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        call do_stagger_fields_exchanges( mytime,myiter,mythid )
        call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      endif
      if (debugmode) then
        call debug_call( 'DYNAMICS',mythid )
      endif
      call timer_start( 'DYNAMICS            [FORWARD_STEP]',mythid )
      call dynamics( mytime,myiter,mythid )
      call timer_stop( 'DYNAMICS            [FORWARD_STEP]',mythid )
      myiter = niter0+iloop
      mytime = starttime+deltatclock*iloop
      if (usemnc) then
        call mnc_update_time( mytime,myiter,mythid )
      endif
      if (momstepping) then
        call timer_start( 'SOLVE_FOR_PRESSURE  [FORWARD_STEP]',mythid )
        call solve_for_pressure( mytime,myiter,mythid )
        call timer_stop( 'SOLVE_FOR_PRESSURE  [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'MOM_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call momentum_correction_step( mytime,myiter,mythid )
      call timer_stop( 'MOM_CORRECTION_STEP [FORWARD_STEP]',mythid )
      if (calc_wvelocity) then
        call timer_start( 'INTEGR_CONTINUITY   [FORWARD_STEP]',mythid )
        call integr_continuity( uvel,vvel,mytime,myiter,mythid )
        call timer_stop( 'INTEGR_CONTINUITY   [FORWARD_STEP]',mythid )
      endif
      if (staggertimestep) then
        if (debugmode) then
          call debug_call( 'DO_STAGGER_FIELDS_EXCH.',mythid )
        endif
        call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        call do_stagger_fields_exchanges( mytime,myiter,mythid )
        call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
        if (usediagnostics) then
          call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
          call do_statevars_diags( mytime,1,myiter,mythid )
          call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        endif
        if (debugmode) then
          call debug_call( 'THERMODYNAMICS',mythid )
        endif
        call timer_start( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
        call thermodynamics( mytime,myiter,mythid )
        call timer_stop( 'THERMODYNAMICS      [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'TRC_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call tracers_correction_step( mytime,myiter,mythid )
      call timer_stop( 'TRC_CORRECTION_STEP [FORWARD_STEP]',mythid )
      call timer_start( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      call do_fields_blocking_exchanges( mythid )
      call timer_stop( 'BLOCKING_EXCHANGES  [FORWARD_STEP]',mythid )
      if (useihop) then
        call ihop_sound_speed( mythid )
        call timer_start( 'IHOP_DRIVER           [FORWARD_STEP]',mythid )
        call ihop_driver( mytime,myiter,mythid )
        call timer_stop( 'IHOP_DRIVER           [FORWARD_STEP]',mythid )
      endif
      if (usediagnostics) then
        call timer_start( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
        call do_statevars_diags( mytime,2,myiter,mythid )
        call timer_stop( 'DO_STATEVARS_DIAGS  [FORWARD_STEP]',mythid )
      endif
      if (monitorfreq > 0. .or. adjmonitorfreq > 0.) then
        call timer_start( 'MONITOR             [FORWARD_STEP]',mythid )
        call monitor( mytime,myiter,mythid )
        call timer_stop( 'MONITOR             [FORWARD_STEP]',mythid )
      endif
      call timer_start( 'COST_TILE           [FORWARD_STEP]',mythid )
      call cost_tile( mytime,myiter,mythid )
      call timer_stop( 'COST_TILE           [FORWARD_STEP]',mythid )
      if (useecco) then
        call ecco_phys( mytime,myiter,mythid )
      endif
      modelend = mytime == endtime .or. myiter == nenditer
      if (usesigreg) then
        modelend = modelend .or. i_got_signal > 0
      endif
      call timer_start( 'DO_THE_MODEL_IO     [FORWARD_STEP]',mythid )
      call do_the_model_io( modelend,mytime,myiter,mythid )
      call timer_stop( 'DO_THE_MODEL_IO     [FORWARD_STEP]',mythid )
      call timer_start( 'DO_WRITE_PICKUP     [FORWARD_STEP]',mythid )
      call do_write_pickup( modelend,mytime,myiter,mythid )
      call timer_stop( 'DO_WRITE_PICKUP     [FORWARD_STEP]',mythid )
      if (usesigreg) then
        if (modelend .and. i_got_signal > 0) then
          stop 'Checkpoint completed -- killed by signal handler'
        endif
      endif
      call autodiff_inadmode_set( mytime,myiter,mythid )
      if (debugmode) then
        call debug_leave( 'FORWARD_STEP',mythid )
      endif
      end subroutine forward_step
