C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_sound_speed_tl( mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      double precision, parameter :: oners = 1.0d0
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      double precision :: ahybsigmc(nr)
      double precision :: ahybsigmf(nr+1)
      double precision :: anglecosc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: anglesinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: bhybsigmc(nr)
      double precision :: bhybsigmf(nr+1)
      double precision :: dahybsigc(nr+1)
      double precision :: dahybsigf(nr)
      double precision :: dbhybsigc(nr+1)
      double precision :: dbhybsigf(nr)
      double precision :: drc(nr+1)
      double precision :: drf(nr)
      double precision :: dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcori(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcoricos(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcorig(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskins(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskinw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: masks(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rc(nr)
      double precision :: recip_drc(nr+1)
      double precision :: recip_drf(nr)
      double precision :: recip_dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rf(nr+1)
      double precision :: rlows(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rloww(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ro_surf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfs(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: u2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: v2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_rs/ dxc, dxf, dxg, dxv, dyc, dyf, dyg, dyu, rloww, rlows, ro_surf, rsurfw, rsurfs, recip_dxc, recip_dxf, 
     $recip_dxg, recip_dxv, recip_dyc, recip_dyf, recip_dyg, recip_dyu, xc, yc, ra, raw, ras, raz, xg, yg, maskinc, maskinw, 
     $maskins, maskc, maskw, masks, recip_ra, recip_raw, recip_ras, recip_raz, drc, drf, recip_drc, recip_drf, rc, rf, ahybsigmf, 
     $bhybsigmf, ahybsigmc, bhybsigmc, dahybsigf, dbhybsigf, dbhybsigc, dahybsigc, tanphiatu, tanphiatv, anglecosc, anglesinc, 
     $u2zondir, v2zondir, fcori, fcorig, fcoricos

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      double precision :: ihop_ssp_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d_tl/ ihop_ssp_tl

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

C==============================================
C declare arguments
C==============================================
      integer, intent(in) :: mythid

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      logical :: calc_soundspeed
      logical :: help_h
      integer :: i
      integer :: j
      integer :: k

C==============================================
C declare external procedures and functions
C==============================================
      external :: chen_millero_tl
      logical, external :: diagnostics_is_on

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      calc_soundspeed =  .true. 
      if (usediagnostics) then
        calc_soundspeed = calc_soundspeed .or. diagnostics_is_on('SVEL    ',mythid) .or. diagnostics_is_on('SLD     ',mythid)
      endif
      if (calc_soundspeed) then
        do bj = mybylo(mythid), mybyhi(mythid)
          do bi = mybxlo(mythid), mybxhi(mythid)
            do k = 1, nr
              do j = 1-oly, sny+oly
                do i = 1-olx, snx+olx
                  ihop_ssp_tl(i,j,k,bi,bj) = 0.d0
                  ihop_ssp(i,j,k,bi,bj) = 0.0d0
                end do
              end do
            end do
            do k = 1, nr
              do j = 1, sny
                do i = 1, snx
                  if (maskc(i,j,k,bi,bj) == oners) then
                    call chen_millero_tl( ihop_ssp(i,j,k,bi,bj),ihop_ssp_tl(i,j,k,bi,bj),i,j,k,bi,bj,mythid )
                  endif
                end do
              end do
            end do
          end do
        end do
      endif
      help_h = usediagnostics .and. diagnostics_is_on('SLD     ',mythid)
      if (help_h) then
        do bj = mybylo(mythid), mybyhi(mythid)
          do bi = mybxlo(mythid), mybxhi(mythid)
            call ihop_calc_sld( bi,bj,mythid )
          end do
        end do
      endif

      end subroutine ihop_sound_speed_tl

      subroutine ihop_sound_speed( mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      double precision, parameter :: oners = 1.0d0
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      double precision :: ahybsigmc(nr)
      double precision :: ahybsigmf(nr+1)
      double precision :: anglecosc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: anglesinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: bhybsigmc(nr)
      double precision :: bhybsigmf(nr+1)
      double precision :: dahybsigc(nr+1)
      double precision :: dahybsigf(nr)
      double precision :: dbhybsigc(nr+1)
      double precision :: dbhybsigf(nr)
      double precision :: drc(nr+1)
      double precision :: drf(nr)
      double precision :: dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcori(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcoricos(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: fcorig(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskc(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskinc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskins(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: maskinw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: masks(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: maskw(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      double precision :: ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rc(nr)
      double precision :: recip_drc(nr+1)
      double precision :: recip_drf(nr)
      double precision :: recip_dxc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dxv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_dyu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ra(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_ras(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: recip_raz(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rf(nr+1)
      double precision :: rlows(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rloww(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: ro_surf(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfs(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: rsurfw(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatu(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: tanphiatv(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: u2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: v2zondir(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: xg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yc(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      double precision :: yg(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /grid_rs/ dxc, dxf, dxg, dxv, dyc, dyf, dyg, dyu, rloww, rlows, ro_surf, rsurfw, rsurfs, recip_dxc, recip_dxf, 
     $recip_dxg, recip_dxv, recip_dyc, recip_dyf, recip_dyg, recip_dyu, xc, yc, ra, raw, ras, raz, xg, yg, maskinc, maskinw, 
     $maskins, maskc, maskw, masks, recip_ra, recip_raw, recip_ras, recip_raz, drc, drf, recip_drc, recip_drf, rc, rf, ahybsigmf, 
     $bhybsigmf, ahybsigmc, bhybsigmc, dahybsigf, dbhybsigf, dbhybsigc, dahybsigc, tanphiatu, tanphiatv, anglecosc, anglesinc, 
     $u2zondir, v2zondir, fcori, fcorig, fcoricos

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

C==============================================
C declare arguments
C==============================================
      integer :: mythid

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      logical :: calc_soundspeed
      logical :: help_h
      integer :: i
      integer :: j
      integer :: k

C==============================================
C declare external procedures and functions
C==============================================
      double precision, external :: chen_millero
      logical, external :: diagnostics_is_on

      calc_soundspeed =  .true. 
      if (usediagnostics) then
        calc_soundspeed = calc_soundspeed .or. diagnostics_is_on('SVEL    ',mythid) .or. diagnostics_is_on('SLD     ',mythid)
      endif
      if (calc_soundspeed) then
        do bj = mybylo(mythid), mybyhi(mythid)
          do bi = mybxlo(mythid), mybxhi(mythid)
            do k = 1, nr
              do j = 1-oly, sny+oly
                do i = 1-olx, snx+olx
                  ihop_ssp(i,j,k,bi,bj) = 0.0d0
                end do
              end do
            end do
            do k = 1, nr
              do j = 1, sny
                do i = 1, snx
                  if (maskc(i,j,k,bi,bj) == oners) then
                    ihop_ssp(i,j,k,bi,bj) = chen_millero(i,j,k,bi,bj,mythid)
                  endif
                end do
              end do
            end do
          end do
        end do
      endif
      help_h = usediagnostics .and. diagnostics_is_on('SLD     ',mythid)
      if (help_h) then
        do bj = mybylo(mythid), mybyhi(mythid)
          do bi = mybxlo(mythid), mybxhi(mythid)
            call ihop_calc_sld( bi,bj,mythid )
          end do
        end do
      endif
      end subroutine ihop_sound_speed
