C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_init_varia_tl()
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      double precision :: ihop_ssp_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d_tl/ ihop_ssp_tl

C----------------------------------------------
C RESET LOCAL TANGENT VARIABLES
C----------------------------------------------
      ihop_ssp_tl(:,:,:,:,:) = 0.d0

      end subroutine ihop_init_varia_tl

      subroutine ihop_init_varia( mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_len_fnam = 512
      integer, parameter :: max_len_prec = 200
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 62
      integer, parameter :: sny = 62

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      double precision :: ihop_sld(1-olx:snx+olx,1-oly:sny+oly,nsx,nsy)
      common /ihop_state_2d/ ihop_sld

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      character(len=max_len_fnam) :: addmassfile
      character(len=max_len_fnam) :: addswallfile
      character(len=max_len_fnam) :: addwwallfile
      character(len=max_len_fnam) :: adtapedir
      character(len=max_len_fnam) :: bathyfile
      character(len=max_len_fnam) :: buoyancyrelation
      character(len=max_len_fnam) :: delrcfile
      character(len=max_len_fnam) :: delrfile
      character(len=max_len_fnam) :: delxfile
      character(len=max_len_fnam) :: delyfile
      character(len=max_len_fnam) :: diffkrfile
      character(len=max_len_fnam) :: eddypsixfile
      character(len=max_len_fnam) :: eddypsiyfile
      character(len=max_len_fnam) :: empmrfile
      character(len=6) :: eostype
      character(len=max_len_fnam) :: geopotanomfile
      character(len=max_len_fnam) :: geothermalfile
      character(len=max_len_fnam) :: gravityfile
      character(len=max_len_fnam) :: horizgridfile
      character(len=max_len_fnam) :: hybsigmfile
      character(len=max_len_fnam) :: hydrogsaltfile
      character(len=max_len_fnam) :: hydrogthetafile
      character(len=max_len_fnam) :: lambdasaltfile
      character(len=max_len_fnam) :: lambdathetafile
      character(len=max_len_fnam) :: mdsiolocaldir
      character(len=max_len_fnam) :: meridwindfile
      character(len=10) :: pickupsuff
      character(len=max_len_fnam) :: ploadfile
      character(len=max_len_fnam) :: psurfinitfile
      character(len=max_len_fnam) :: rhoreffile
      character(len=max_len_fnam) :: saltclimfile
      character(len=max_len_fnam) :: saltfluxfile
      character(len=max_len_fnam) :: sreffile
      character(len=max_len_fnam) :: surfqfile
      character(len=max_len_fnam) :: surfqnetfile
      character(len=max_len_fnam) :: surfqswfile
      character(len=max_len_prec/2) :: the_run_name
      character(len=max_len_fnam) :: thetaclimfile
      character(len=max_len_fnam) :: topofile
      character(len=max_len_fnam) :: treffile
      character(len=max_len_fnam) :: uvelinitfile
      character(len=max_len_fnam) :: visca4dfile
      character(len=max_len_fnam) :: visca4zfile
      character(len=max_len_fnam) :: viscahdfile
      character(len=max_len_fnam) :: viscahzfile
      character(len=max_len_fnam) :: vvelinitfile
      character(len=max_len_fnam) :: wghtbalancefile
      character(len=max_len_fnam) :: zonalwindfile
      common /parm_c/ buoyancyrelation, eostype, pickupsuff, mdsiolocaldir, adtapedir, treffile, sreffile, rhoreffile, gravityfile, 
     $delrfile, delrcfile, hybsigmfile, delxfile, delyfile, horizgridfile, bathyfile, topofile, addwwallfile, addswallfile, 
     $viscahdfile, viscahzfile, visca4dfile, visca4zfile, hydrogthetafile, hydrogsaltfile, diffkrfile, zonalwindfile, meridwindfile,
     $ thetaclimfile, saltclimfile, empmrfile, saltfluxfile, surfqfile, surfqnetfile, surfqswfile, uvelinitfile, vvelinitfile, 
     $psurfinitfile, ploadfile, geopotanomfile, addmassfile, eddypsixfile, eddypsiyfile, geothermalfile, lambdathetafile, 
     $lambdasaltfile, wghtbalancefile, the_run_name

      integer :: cg2dmaxiters
      integer :: cg2dminitersnsa
      integer :: cg2dprecondfreq
      integer :: cg2duseminressol
      integer :: cg3dmaxiters
      integer :: debuglevel
      integer :: momforcingoutab
      integer :: monitorselect
      integer :: nenditer
      integer :: niter0
      integer :: nonlinfreesurf
      integer :: ntimesteps
      integer :: ntimesteps_l2
      integer :: pcellmix_select
      integer :: plotlevel
      integer :: printresidualfreq
      integer :: readbinaryprec
      integer :: rwsuffixtype
      integer :: saltadvscheme
      integer :: saltvertadvscheme
      integer :: select3dcorischeme
      integer :: select_rstar
      integer :: selectaddfluid
      integer :: selectbalanceempmr
      integer :: selectbotdragquadr
      integer :: selectcorimap
      integer :: selectcorischeme
      integer :: selectimplicitdrag
      integer :: selectkescheme
      integer :: selectmetricterms
      integer :: selectnhfreesurf
      integer :: selectp_ineos_zc
      integer :: selectpenetratingsw
      integer :: selectsigmacoord
      integer :: selectvortscheme
      integer :: tempadvscheme
      integer :: tempvertadvscheme
      integer :: tracforcingoutab
      integer :: writebinaryprec
      common /parm_i/ cg2dmaxiters, cg2dminitersnsa, cg2dprecondfreq, cg2duseminressol, cg3dmaxiters, printresidualfreq, niter0, 
     $ntimesteps, ntimesteps_l2, nenditer, selectcorimap, selectsigmacoord, nonlinfreesurf, select_rstar, selectnhfreesurf, 
     $selectp_ineos_zc, selectaddfluid, selectbalanceempmr, selectimplicitdrag, momforcingoutab, tracforcingoutab, tempadvscheme, 
     $tempvertadvscheme, saltadvscheme, saltvertadvscheme, selectkescheme, selectvortscheme, selectmetricterms, selectcorischeme, 
     $select3dcorischeme, selectbotdragquadr, selectpenetratingsw, pcellmix_select, readbinaryprec, writebinaryprec, rwsuffixtype, 
     $monitorselect, debuglevel, plotlevel

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

C==============================================
C declare arguments
C==============================================
      integer :: mythid

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      integer :: i
      integer :: j
      integer :: k

      do bj = mybylo(mythid), mybyhi(mythid)
        do bi = mybxlo(mythid), mybxhi(mythid)
          do k = 1, nr
            do j = 1-oly, sny+oly
              do i = 1-olx, snx+olx
                ihop_ssp(i,j,k,bi,bj) = 0.d0
              end do
            end do
          end do
          do j = 1-oly, sny+oly
            do i = 1-olx, snx+olx
              ihop_sld(i,j,bi,bj) = 0.d0
            end do
          end do
        end do
      end do
      if (starttime == basetime .and. niter0 == 0 .and. pickupsuff == ' ') then
      else
        call ihop_read_pickup( niter0,mythid )
      endif
      end subroutine ihop_init_varia
