C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_cost_tl( mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_len_mbuf = 512
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 31
      integer, parameter :: sny = 31
      character(len=*), parameter :: squeeze_right = 'R'
      double precision, parameter :: zerorl = 0.0d0

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      integer :: ihopobs_i_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_ind_glob(nfilesmax_ihop,nobsmax_ihop)
      integer :: ihopobs_ind_glob_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_j_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_k_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_sample1_ind(nfilesmax_ihop,nobsmax_ihop)
      integer :: ncidad(nfilesmax_ihop,nsx,nsy)
      integer :: ncidadglob(nfilesmax_ihop)
      integer :: nciddata(nfilesmax_ihop)
      integer :: ncidfwd(nfilesmax_ihop,nsx,nsy)
      integer :: ncidglob(nfilesmax_ihop)
      integer :: ncidtl(nfilesmax_ihop,nsx,nsy)
      integer :: ncidtlglob(nfilesmax_ihop)
      integer :: obsno(nfilesmax_ihop)
      integer :: obsno_tiled(nfilesmax_ihop,nsx,nsy)
      common /ihop_cost_i/ obsno, obsno_tiled, ihopobs_ind_glob, ihopobs_ind_glob_tiled, ncidfwd, ncidad, ncidtl, ncidglob, 
     $ncidadglob, ncidtlglob, nciddata, ihopobs_i_tiled, ihopobs_j_tiled, ihopobs_k_tiled, ihopobs_sample1_ind

      logical :: ihopdoncoutput
      common /ihop_cost_l/ ihopdoncoutput

      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

      double precision :: objf_ihop_tl(nfilesmax_ihop)
      common /ihop_cost_r_tl/ objf_ihop_tl

      double precision :: ihop_dummy(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy(nfilesmax_ihop)
      common /ihop_ctrl_dummy/ ihop_dummy, ihop_globaldummy

      double precision :: ihop_dummy_tl(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy_tl(nfilesmax_ihop)
      common /ihop_ctrl_dummy_tl/ ihop_dummy_tl, ihop_globaldummy_tl

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      double precision :: ihop_ssp_tl(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d_tl/ ihop_ssp_tl

      integer :: optimcycle
      common /optiparm_i/ optimcycle

C==============================================
C declare arguments
C==============================================
      integer :: myiter
      integer, intent(inout) :: mythid
      double precision :: mytime

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      integer :: err
      double precision :: ihop_data
      double precision :: ihop_modval
      double precision :: ihop_modval_tl
      double precision :: ihop_modvaltmp
      double precision :: ihop_modvaltmp_tl
      double precision :: ihop_uncert
      double precision :: ihop_weight
      double precision :: ihopobs_buff(nobsmax_ihop)
      double precision :: ihopobs_buff_tl(nobsmax_ihop)
      double precision :: ihopobs_modval_glob(nobsmax_ihop)
      double precision :: ihopobs_modval_glob_tl(nobsmax_ihop)
      integer :: iobs
      integer :: irec
      character(len=max_len_mbuf) :: msgbuf
      integer :: num_file
      double precision :: num_ihop_glo
      double precision :: objf_ihop_glo
      double precision :: tmpgs
      double precision :: tmpgs_tl

C==============================================
C declare external procedures and functions
C==============================================
      integer, external :: nf_sync

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      write(unit=msgbuf,fmt='(A)') ' '
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      write(unit=msgbuf,fmt='(A)') '== ihop_cost: begin =='
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      if (mythid == 1) then
        do num_file = 1, nfilesmax_ihop
          do bj = 1, nsy
            do bi = 1, nsx
              if (obsno_tiled(num_file,bi,bj) > 0 .and. ihopdoncoutput) then
                err = nf_sync(ncidfwd(num_file,bi,bj))
                call ihop_cost_nf_error( 'ihop_cost 1',err,bi,bj,mythid )
              endif
            end do
          end do
          do iobs = 1, nobsmax_ihop
            ihopobs_buff_tl(iobs) = 0.d0
            ihopobs_buff(iobs) = zerorl
          end do
          do bj = 1, nsy
            do bi = 1, nsx
              do iobs = 1, nobsmax_ihop
                if (iobs <= obsno_tiled(num_file,bi,bj)) then
                  ihop_modvaltmp_tl = 0.d0
                  ihop_modvaltmp = zerorl
                  call g_active_read_ihop_tile( num_file,ihop_modvaltmp,ihop_modvaltmp_tl,iobs, .false. ,optimcycle,bi,bj,mythid,
     $ihop_dummy(num_file,bi,bj) )
                  irec = ihopobs_ind_glob_tiled(num_file,iobs,bi,bj)
                  ihopobs_buff_tl(irec) = ihop_ssp_tl(1,1,1,bi,bj)+ihop_modvaltmp_tl+ihopobs_buff_tl(irec)
                  ihopobs_buff(irec) = ihopobs_buff(irec)+ihop_modvaltmp+ihop_ssp(1,1,1,bi,bj)
                  ihopobs_buff_tl(irec) = (-ihop_ssp_tl(1,1,1,bi,bj))+ihopobs_buff_tl(irec)
                  ihopobs_buff(irec) = ihopobs_buff(irec)-ihop_ssp(1,1,1,bi,bj)
                endif
              end do
            end do
          end do
          do iobs = 1, nobsmax_ihop
            tmpgs_tl = ihopobs_buff_tl(iobs)
            tmpgs = ihopobs_buff(iobs)
            call global_sum_r8( tmpgs_tl,mythid )
            call global_sum_r8( tmpgs,mythid )
            ihopobs_modval_glob_tl(iobs) = tmpgs_tl
            ihopobs_modval_glob(iobs) = tmpgs
          end do
          if (myprocid == 0) then
            do iobs = 1, nobsmax_ihop
              if (iobs <= obsno(num_file)) then
                ihop_modval_tl = 0.d0
                ihop_modval = zerorl
                ihop_modval_tl = ihop_modval_tl+ihopobs_modval_glob_tl(iobs)
                ihop_modval = ihop_modval+ihopobs_modval_glob(iobs)
                call g_active_write_ihop_glob( num_file,ihop_modval,ihop_modval_tl,iobs,optimcycle,mythid,ihop_globaldummy(num_file)
     $,ihop_globaldummy_tl(num_file) )
              endif
            end do
            err = nf_sync(ncidglob(num_file))
            call ihop_cost_nf_error( 'IHOP_COST: NF_SYNC ncidGLOB',err,0,0,mythid )
            do iobs = 1, nobsmax_ihop
              if (iobs <= obsno(num_file)) then
                ihop_modval_tl = 0.d0
                ihop_modval = zerorl
                ihop_data = zerorl
                ihop_uncert = zerorl
                call g_active_read_ihop_glob( num_file,ihop_modval,ihop_modval_tl,iobs, .false. ,optimcycle,mythid,ihop_globaldummy(
     $num_file) )
                ihop_uncert = 1.d0
                if (ihop_data == (-9999)) then
                  ihop_uncert = zerorl
                endif
                if (ihop_uncert > zerorl) then
                  ihop_weight = 1.d0/(ihop_uncert*ihop_uncert)
                  objf_ihop_tl(num_file) = 2*ihop_modval_tl*(ihop_weight*(ihop_modval-ihop_data))+objf_ihop_tl(num_file)
                  objf_ihop(num_file) = objf_ihop(num_file)+ihop_weight*(ihop_modval-ihop_data)*(ihop_modval-ihop_data)
                  num_ihop(num_file) = num_ihop(num_file)+1
                endif
              endif
            end do
          endif
        end do
      endif
      do num_file = 1, nfilesmax_ihop
        objf_ihop_glo = objf_ihop(num_file)
        num_ihop_glo = num_ihop(num_file)
        write(unit=msgbuf,fmt='(A,I2,A,2D12.5)') ' ihop_cost(',num_file,' )= ',objf_ihop_glo,num_ihop_glo
        if (num_ihop_glo > zerorl) then
          call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
        endif
      end do
      write(unit=msgbuf,fmt='(A)') '== ihop_cost: end   =='
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      write(unit=msgbuf,fmt='(A)') ' '
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )

      end subroutine ihop_cost_tl

      subroutine ihop_cost( mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: max_len_mbuf = 512
      integer, parameter :: max_no_threads = 4
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1
      integer, parameter :: olx = 3
      integer, parameter :: oly = 3
      integer, parameter :: snx = 31
      integer, parameter :: sny = 31
      character(len=*), parameter :: squeeze_right = 'R'
      double precision, parameter :: zerorl = 0.0d0

C==============================================
C declare common blocks
C==============================================
      integer :: eedataunit
      integer :: errormessageunit
      integer :: ioerrorcount(max_no_threads)
      integer :: maxlengthprt1d
      integer :: modeldataunit
      integer :: mybxhi(max_no_threads)
      integer :: mybxlo(max_no_threads)
      integer :: mybyhi(max_no_threads)
      integer :: mybylo(max_no_threads)
      integer :: myprocid
      integer :: mypx
      integer :: mypy
      integer :: myxgloballo
      integer :: myygloballo
      integer :: nthreads
      integer :: ntx
      integer :: nty
      integer :: numberofprocs
      integer :: pidio
      integer :: scrunit1
      integer :: scrunit2
      integer :: standardmessageunit
      common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, 
     $numberofprocs, pidio, myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, 
     $ioerrorcount

      integer :: ihopobs_i_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_ind_glob(nfilesmax_ihop,nobsmax_ihop)
      integer :: ihopobs_ind_glob_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_j_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_k_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_sample1_ind(nfilesmax_ihop,nobsmax_ihop)
      integer :: ncidad(nfilesmax_ihop,nsx,nsy)
      integer :: ncidadglob(nfilesmax_ihop)
      integer :: nciddata(nfilesmax_ihop)
      integer :: ncidfwd(nfilesmax_ihop,nsx,nsy)
      integer :: ncidglob(nfilesmax_ihop)
      integer :: ncidtl(nfilesmax_ihop,nsx,nsy)
      integer :: ncidtlglob(nfilesmax_ihop)
      integer :: obsno(nfilesmax_ihop)
      integer :: obsno_tiled(nfilesmax_ihop,nsx,nsy)
      common /ihop_cost_i/ obsno, obsno_tiled, ihopobs_ind_glob, ihopobs_ind_glob_tiled, ncidfwd, ncidad, ncidtl, ncidglob, 
     $ncidadglob, ncidtlglob, nciddata, ihopobs_i_tiled, ihopobs_j_tiled, ihopobs_k_tiled, ihopobs_sample1_ind

      logical :: ihopdoncoutput
      common /ihop_cost_l/ ihopdoncoutput

      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

      double precision :: ihop_dummy(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy(nfilesmax_ihop)
      common /ihop_ctrl_dummy/ ihop_dummy, ihop_globaldummy

      double precision :: ihop_ssp(1-olx:snx+olx,1-oly:sny+oly,nr,nsx,nsy)
      common /ihop_state_3d/ ihop_ssp

      integer :: optimcycle
      common /optiparm_i/ optimcycle

C==============================================
C declare arguments
C==============================================
      integer :: myiter
      integer :: mythid
      double precision :: mytime

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      integer :: err
      double precision :: ihop_data
      double precision :: ihop_modval
      double precision :: ihop_modvaltmp
      double precision :: ihop_uncert
      double precision :: ihop_weight
      double precision :: ihopobs_buff(nobsmax_ihop)
      double precision :: ihopobs_modval_glob(nobsmax_ihop)
      integer :: iobs
      integer :: irec
      character(len=max_len_mbuf) :: msgbuf
      integer :: num_file
      double precision :: num_ihop_glo
      double precision :: objf_ihop_glo
      double precision :: tmpgs

C==============================================
C declare external procedures and functions
C==============================================
      integer, external :: nf_sync

      write(unit=msgbuf,fmt='(A)') ' '
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      write(unit=msgbuf,fmt='(A)') '== ihop_cost: begin =='
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      if (mythid == 1) then
        do num_file = 1, nfilesmax_ihop
          do bj = 1, nsy
            do bi = 1, nsx
              if (obsno_tiled(num_file,bi,bj) > 0 .and. ihopdoncoutput) then
                err = nf_sync(ncidfwd(num_file,bi,bj))
                call ihop_cost_nf_error( 'ihop_cost 1',err,bi,bj,mythid )
              endif
            end do
          end do
          do iobs = 1, nobsmax_ihop
            ihopobs_buff(iobs) = zerorl
          end do
          do bj = 1, nsy
            do bi = 1, nsx
              do iobs = 1, nobsmax_ihop
                if (iobs <= obsno_tiled(num_file,bi,bj)) then
                  ihop_modvaltmp = zerorl
                  call active_read_ihop_tile( num_file,ihop_modvaltmp,iobs, .false. ,optimcycle,bi,bj,mythid,ihop_dummy(num_file,bi,
     $bj) )
                  irec = ihopobs_ind_glob_tiled(num_file,iobs,bi,bj)
                  ihopobs_buff(irec) = ihopobs_buff(irec)+ihop_modvaltmp+ihop_ssp(1,1,1,bi,bj)
                  ihopobs_buff(irec) = ihopobs_buff(irec)-ihop_ssp(1,1,1,bi,bj)
                endif
              end do
            end do
          end do
          do iobs = 1, nobsmax_ihop
            tmpgs = ihopobs_buff(iobs)
            call global_sum_r8( tmpgs,mythid )
            ihopobs_modval_glob(iobs) = tmpgs
          end do
          if (myprocid == 0) then
            do iobs = 1, nobsmax_ihop
              if (iobs <= obsno(num_file)) then
                ihop_modval = zerorl
                ihop_modval = ihop_modval+ihopobs_modval_glob(iobs)
                call active_write_ihop_glob( num_file,ihop_modval,iobs,optimcycle,mythid,ihop_globaldummy(num_file) )
              endif
            end do
            err = nf_sync(ncidglob(num_file))
            call ihop_cost_nf_error( 'IHOP_COST: NF_SYNC ncidGLOB',err,0,0,mythid )
            do iobs = 1, nobsmax_ihop
              if (iobs <= obsno(num_file)) then
                ihop_modval = zerorl
                ihop_data = zerorl
                ihop_uncert = zerorl
                call active_read_ihop_glob( num_file,ihop_modval,iobs, .false. ,optimcycle,mythid,ihop_globaldummy(num_file) )
                ihop_uncert = 1.d0
                if (ihop_data == (-9999)) then
                  ihop_uncert = zerorl
                endif
                if (ihop_uncert > zerorl) then
                  ihop_weight = 1.d0/(ihop_uncert*ihop_uncert)
                  objf_ihop(num_file) = objf_ihop(num_file)+ihop_weight*(ihop_modval-ihop_data)*(ihop_modval-ihop_data)
                  num_ihop(num_file) = num_ihop(num_file)+1
                endif
              endif
            end do
          endif
        end do
      endif
      do num_file = 1, nfilesmax_ihop
        objf_ihop_glo = objf_ihop(num_file)
        num_ihop_glo = num_ihop(num_file)
        write(unit=msgbuf,fmt='(A,I2,A,2D12.5)') ' ihop_cost(',num_file,' )= ',objf_ihop_glo,num_ihop_glo
        if (num_ihop_glo > zerorl) then
          call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
        endif
      end do
      write(unit=msgbuf,fmt='(A)') '== ihop_cost: end   =='
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      write(unit=msgbuf,fmt='(A)') ' '
      call print_message( msgbuf,standardmessageunit,squeeze_right,mythid )
      end subroutine ihop_cost
