C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine packages_init_variables_tl( mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare common blocks
C==============================================
      logical :: debugmode
      logical :: eebooterror
      logical :: eeenderror
      logical :: fatalerror
      logical :: printmapincludeszeros
      logical :: usecoupler
      logical :: usecubedsphereexchange
      logical :: usenest2w_child
      logical :: usenest2w_parent
      logical :: usenest_child
      logical :: usenest_parent
      logical :: useoasis
      logical :: usesetrlstk
      logical :: usesigreg
      logical :: usesinglecpuinput
      logical :: usesinglecpuio
      common /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, 
     $usecubedsphereexchange, usecoupler, usenest_parent, usenest_child, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, 
     $usesigreg

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

C==============================================
C declare arguments
C==============================================
      integer, intent(inout) :: mythid

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      if (debugmode) then
        call debug_enter( 'PACKAGES_INIT_VARIABLES',mythid )
      endif
      if (usediagnostics) then
        call diagnostics_init_varia( mythid )
      endif
      if (usegad) then
        if (debugmode) then
          call debug_call( 'GAD_INIT_VARIA',mythid )
        endif
        call gad_init_varia( mythid )
      endif
      if (useihop) then
        call ihop_init_varia_tl
        call ihop_init_varia( mythid )
      endif
      if (useihop) then
        call ihop_cost_init_varia_tl
        call ihop_cost_init_varia( mythid )
      endif
      if (useecco) then
        call ecco_init_varia_tl( mythid )
      endif
      if (debugmode) then
        call debug_call( 'CTRL_INIT_VARIABLES',mythid )
      endif
      call ctrl_init_variables_tl( mythid )
      if (debugmode) then
        call debug_leave( 'PACKAGES_INIT_VARIABLES',mythid )
      endif

      end subroutine packages_init_variables_tl

      subroutine packages_init_variables( mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
      implicit none

C==============================================
C declare common blocks
C==============================================
      logical :: debugmode
      logical :: eebooterror
      logical :: eeenderror
      logical :: fatalerror
      logical :: printmapincludeszeros
      logical :: usecoupler
      logical :: usecubedsphereexchange
      logical :: usenest2w_child
      logical :: usenest2w_parent
      logical :: usenest_child
      logical :: usenest_parent
      logical :: useoasis
      logical :: usesetrlstk
      logical :: usesigreg
      logical :: usesinglecpuinput
      logical :: usesinglecpuio
      common /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, 
     $usecubedsphereexchange, usecoupler, usenest_parent, usenest_child, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, 
     $usesigreg

      logical :: useaim
      logical :: useatm2d
      logical :: useatm_phys
      logical :: useautodiff
      logical :: usebbl
      logical :: usebulkforce
      logical :: usecal
      logical :: usecheapaml
      logical :: usectrl
      logical :: usediagnostics
      logical :: usedown_slope
      logical :: useebm
      logical :: useecco
      logical :: useembed_files
      logical :: useexf
      logical :: usefizhi
      logical :: useflt
      logical :: usefrazil
      logical :: usegad
      logical :: usegchem
      logical :: useggl90
      logical :: usegmredi
      logical :: usegrdchk
      logical :: usegridalt
      logical :: useicefront
      logical :: useihop
      logical :: usekl10
      logical :: usekpp
      logical :: useland
      logical :: uselayers
      logical :: usematrix
      logical :: usemnc
      logical :: usemy82
      logical :: usemypackage
      logical :: useobcs
      logical :: useoffline
      logical :: useopps
      logical :: usepp81
      logical :: useprofiles
      logical :: useptracers
      logical :: userbcs
      logical :: useregrid
      logical :: userunclock
      logical :: usesalt_plume
      logical :: usesbo
      logical :: useseaice
      logical :: useshap_filt
      logical :: useshelfice
      logical :: usesmooth
      logical :: usestic
      logical :: usestreamice
      logical :: usethsice
      logical :: usezonal_filt
      common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, 
     $usegmredi, usebbl, usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, 
     $useecco, usectrl, usesbo, useflt, useautodiff, useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, 
     $usesalt_plume, useshelfice, usestic, usestreamice, useicefront, usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, 
     $usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, usemypackage, useihop

C==============================================
C declare arguments
C==============================================
      integer :: mythid

      if (debugmode) then
        call debug_enter( 'PACKAGES_INIT_VARIABLES',mythid )
      endif
      if (usediagnostics) then
        call diagnostics_init_varia( mythid )
      endif
      if (usegad) then
        if (debugmode) then
          call debug_call( 'GAD_INIT_VARIA',mythid )
        endif
        call gad_init_varia( mythid )
      endif
      if (useihop) then
        call ihop_init_varia( mythid )
      endif
      if (useihop) then
        call ihop_cost_init_varia( mythid )
      endif
      if (useecco) then
        call ecco_init_varia( mythid )
      endif
      if (debugmode) then
        call debug_call( 'CTRL_INIT_VARIABLES',mythid )
      endif
      call ctrl_init_variables( mythid )
      if (debugmode) then
        call debug_leave( 'PACKAGES_INIT_VARIABLES',mythid )
      endif
      end subroutine packages_init_variables
