!                           DISCLAIMER
! 
!   This file was generated by TAF version 6.8.11
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 
module     ihop_mod
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! write visibility
!==============================================
private
public :: bcastray
public :: bcastray_tl

!==============================================
! declare parameters
!==============================================
integer, public, parameter :: arrfile = 37
integer, public, parameter :: atifile = 41
integer, public, parameter :: brcfile = 38
integer, public, parameter :: btyfile = 42
integer, private, parameter :: cachelinesize = 256
integer, private, parameter :: comm_get = 4
integer, private, parameter :: comm_msg = 2
integer, private, parameter :: comm_none = 1
integer, private, parameter :: comm_put = 3
character(len=*), private, parameter :: commentcharacter = '#'
integer, private, parameter :: debleva = 1
integer, private, parameter :: deblevb = 2
integer, private, parameter :: deblevc = 3
integer, private, parameter :: deblevd = 4
integer, private, parameter :: debleve = 5
integer, private, parameter :: deblevzero = 0
double precision, private, parameter :: pi = 3.14159265358979323844d0
double precision, private, parameter :: deg2rad = 2.d0*pi/360.d0
integer, public, parameter :: delfile = 22
character(len=*), private, parameter :: error_header = ' *** ERROR ***'
integer, private, parameter :: exch_ignore_corners = 0
integer, private, parameter :: exch_update_corners = 1
integer, private, parameter :: forward_simulation = 0
integer, private, parameter :: gsvec_size = 1024
double precision, private, parameter :: halfrl = 0.5d0
double precision, private, parameter :: halfrs = 0.5d0
integer, private, parameter :: index_i = 1
integer, private, parameter :: index_j = 2
integer, private, parameter :: index_k = 3
integer, private, parameter :: index_none = 4
integer, public, parameter :: ircfile = 16
integer, private, parameter :: lshare1 = cachelinesize
integer, private, parameter :: lshare4 = cachelinesize/4
integer, private, parameter :: lshare8 = cachelinesize/8
integer, private, parameter :: max_len_fnam = 512
integer, private, parameter :: max_len_mbuf = 512
integer, private, parameter :: max_len_prec = 200
integer, private, parameter :: max_no_threads = 4
integer, private, parameter :: max_num_comm_modes = 4
integer, private, parameter :: olx = 3
integer, private, parameter :: max_olx = olx
integer, private, parameter :: oly = 3
integer, private, parameter :: max_oly = oly
integer, private, parameter :: mpi_2double_precision = 1275072547
integer, private, parameter :: mpi_2int = 1275070486
integer, private, parameter :: mpi_2integer = 1275070496
integer, private, parameter :: mpi_2real = 1275070497
integer, private, parameter :: mpi_address_kind = 8
integer, private, parameter :: mpi_aint = 1275070531
integer, private, parameter :: mpi_any_source = -2
integer, private, parameter :: mpi_any_tag = -1
integer, private, parameter :: mpi_appnum = 1681915918
logical, private, parameter :: mpi_async_protects_nonblocking =  .false. 
integer, private, parameter :: mpi_band = 1476395014
integer, private, parameter :: mpi_bor = 1476395016
integer, private, parameter :: mpi_bsend_overhead = 88
integer, private, parameter :: mpi_bxor = 1476395018
integer, private, parameter :: mpi_byte = 1275068685
integer, private, parameter :: mpi_c_bool = 1275068735
integer, private, parameter :: mpi_c_complex = 1275070528
integer, private, parameter :: mpi_c_double_complex = 1275072577
integer, private, parameter :: mpi_c_float_complex = 1275070528
integer, private, parameter :: mpi_c_long_double_complex = 1275076674
integer, private, parameter :: mpi_cart = 2
integer, private, parameter :: mpi_char = 1275068673
integer, private, parameter :: mpi_character = 1275068698
integer, private, parameter :: mpi_combiner_contiguous = 3
integer, private, parameter :: mpi_combiner_darray = 14
integer, private, parameter :: mpi_combiner_dup = 2
integer, private, parameter :: mpi_combiner_f90_complex = 16
integer, private, parameter :: mpi_combiner_f90_integer = 17
integer, private, parameter :: mpi_combiner_f90_real = 15
integer, private, parameter :: mpi_combiner_hindexed = 9
integer, private, parameter :: mpi_combiner_hindexed_block = 19
integer, private, parameter :: mpi_combiner_hindexed_integer = 8
integer, private, parameter :: mpi_combiner_hvector = 6
integer, private, parameter :: mpi_combiner_hvector_integer = 5
integer, private, parameter :: mpi_combiner_indexed = 7
integer, private, parameter :: mpi_combiner_indexed_block = 10
integer, private, parameter :: mpi_combiner_named = 1
integer, private, parameter :: mpi_combiner_resized = 18
integer, private, parameter :: mpi_combiner_struct = 12
integer, private, parameter :: mpi_combiner_struct_integer = 11
integer, private, parameter :: mpi_combiner_subarray = 13
integer, private, parameter :: mpi_combiner_vector = 4
integer, private, parameter :: mpi_comm_null = 67108864
integer, private, parameter :: mpi_comm_self = 1140850689
integer, private, parameter :: mpi_comm_type_shared = 1
integer, private, parameter :: mpi_comm_world = 1140850688
integer, private, parameter :: mpi_complex = 1275070494
integer, private, parameter :: mpi_complex16 = 1275072554
integer, private, parameter :: mpi_complex32 = 1275076652
integer, private, parameter :: mpi_complex8 = 1275070504
integer, private, parameter :: mpi_congruent = 1
integer, private, parameter :: mpi_count = 1275070533
integer, private, parameter :: mpi_count_kind = 8
integer, private, parameter :: mpi_cxx_bool = 1275068723
integer, private, parameter :: mpi_cxx_double_complex = 1275072565
integer, private, parameter :: mpi_cxx_float_complex = 1275070516
integer, private, parameter :: mpi_cxx_long_double_complex = 1275076662
integer, private, parameter :: mpi_datatype_null = 201326592
integer(kind=8), private, parameter :: mpi_displacement_current = -54278278
integer, private, parameter :: mpi_dist_graph = 3
integer, private, parameter :: mpi_distribute_block = 121
integer, private, parameter :: mpi_distribute_cyclic = 122
integer, private, parameter :: mpi_distribute_dflt_darg = -49767
integer, private, parameter :: mpi_distribute_none = 123
integer, private, parameter :: mpi_double = 1275070475
integer, private, parameter :: mpi_double_complex = 1275072546
integer, private, parameter :: mpi_double_int = -1946157055
integer, private, parameter :: mpi_double_precision = 1275070495
integer, private, parameter :: mpi_err_access = 20
integer, private, parameter :: mpi_err_amode = 21
integer, private, parameter :: mpi_err_arg = 12
integer, private, parameter :: mpi_err_assert = 53
integer, private, parameter :: mpi_err_bad_file = 22
integer, private, parameter :: mpi_err_base = 46
integer, private, parameter :: mpi_err_buffer = 1
integer, private, parameter :: mpi_err_comm = 5
integer, private, parameter :: mpi_err_conversion = 23
integer, private, parameter :: mpi_err_count = 2
integer, private, parameter :: mpi_err_dims = 11
integer, private, parameter :: mpi_err_disp = 52
integer, private, parameter :: mpi_err_dup_datarep = 24
integer, private, parameter :: mpi_err_file = 27
integer, private, parameter :: mpi_err_file_exists = 25
integer, private, parameter :: mpi_err_file_in_use = 26
integer, private, parameter :: mpi_err_group = 8
integer, private, parameter :: mpi_err_in_status = 17
integer, private, parameter :: mpi_err_info = 28
integer, private, parameter :: mpi_err_info_key = 29
integer, private, parameter :: mpi_err_info_nokey = 31
integer, private, parameter :: mpi_err_info_value = 30
integer, private, parameter :: mpi_err_intern = 16
integer, private, parameter :: mpi_err_io = 32
integer, private, parameter :: mpi_err_keyval = 48
integer, private, parameter :: mpi_err_lastcode = 1073741823
integer, private, parameter :: mpi_err_locktype = 47
integer, private, parameter :: mpi_err_name = 33
integer, private, parameter :: mpi_err_no_mem = 34
integer, private, parameter :: mpi_err_no_space = 36
integer, private, parameter :: mpi_err_no_such_file = 37
integer, private, parameter :: mpi_err_not_same = 35
integer, private, parameter :: mpi_err_op = 9
integer, private, parameter :: mpi_err_other = 15
integer, private, parameter :: mpi_err_pending = 18
integer, private, parameter :: mpi_err_port = 38
integer, private, parameter :: mpi_err_quota = 39
integer, private, parameter :: mpi_err_rank = 6
integer, private, parameter :: mpi_err_read_only = 40
integer, private, parameter :: mpi_err_request = 19
integer, private, parameter :: mpi_err_rma_attach = 56
integer, private, parameter :: mpi_err_rma_conflict = 49
integer, private, parameter :: mpi_err_rma_flavor = 58
integer, private, parameter :: mpi_err_rma_range = 55
integer, private, parameter :: mpi_err_rma_shared = 57
integer, private, parameter :: mpi_err_rma_sync = 50
integer, private, parameter :: mpi_err_root = 7
integer, private, parameter :: mpi_err_service = 41
integer, private, parameter :: mpi_err_size = 51
integer, private, parameter :: mpi_err_spawn = 42
integer, private, parameter :: mpi_err_tag = 4
integer, private, parameter :: mpi_err_topology = 10
integer, private, parameter :: mpi_err_truncate = 14
integer, private, parameter :: mpi_err_type = 3
integer, private, parameter :: mpi_err_unknown = 13
integer, private, parameter :: mpi_err_unsupported_datarep = 43
integer, private, parameter :: mpi_err_unsupported_operation = 44
integer, private, parameter :: mpi_err_win = 45
integer, private, parameter :: mpi_errhandler_null = 335544320
integer, private, parameter :: mpi_error = 5
integer, private, parameter :: mpi_errors_are_fatal = 1409286144
integer, private, parameter :: mpi_errors_return = 1409286145
integer, private, parameter :: mpi_file_null = 0
integer, private, parameter :: mpi_float = 1275069450
integer, private, parameter :: mpi_float_int = -1946157056
integer, private, parameter :: mpi_graph = 1
integer, private, parameter :: mpi_group_empty = 1207959552
integer, private, parameter :: mpi_group_null = 134217728
integer, private, parameter :: mpi_host = 1681915908
integer, private, parameter :: mpi_ident = 0
integer, private, parameter :: mpi_info_env = 1543503873
integer, private, parameter :: mpi_info_null = 469762048
integer, private, parameter :: mpi_int = 1275069445
integer, private, parameter :: mpi_int16_t = 1275068984
integer, private, parameter :: mpi_int32_t = 1275069497
integer, private, parameter :: mpi_int64_t = 1275070522
integer, private, parameter :: mpi_int8_t = 1275068727
integer, private, parameter :: mpi_integer = 1275069467
integer, private, parameter :: mpi_integer1 = 1275068717
integer, private, parameter :: mpi_integer16 = mpi_datatype_null
integer, private, parameter :: mpi_integer2 = 1275068975
integer, private, parameter :: mpi_integer4 = 1275069488
integer, private, parameter :: mpi_integer8 = 1275070513
integer, private, parameter :: mpi_integer_kind = 4
integer, private, parameter :: mpi_io = 1681915910
integer, private, parameter :: mpi_keyval_invalid = 603979776
integer, private, parameter :: mpi_land = 1476395013
integer, private, parameter :: mpi_lastusedcode = 1681915916
integer, private, parameter :: mpi_lb = 1275068432
integer, private, parameter :: mpi_lock_exclusive = 234
integer, private, parameter :: mpi_lock_shared = 235
integer, private, parameter :: mpi_logical = 1275069469
integer, private, parameter :: mpi_long = 1275070471
integer, private, parameter :: mpi_long_double = 1275072524
integer, private, parameter :: mpi_long_double_int = -1946157052
integer, private, parameter :: mpi_long_int = -1946157054
integer, private, parameter :: mpi_long_long = 1275070473
integer, private, parameter :: mpi_long_long_int = 1275070473
integer, private, parameter :: mpi_lor = 1476395015
integer, private, parameter :: mpi_lxor = 1476395017
integer, private, parameter :: mpi_max = 1476395009
integer, private, parameter :: mpi_max_datarep_string = 127
integer, private, parameter :: mpi_max_error_string = 512-1
integer, private, parameter :: mpi_max_info_key = 254
integer, private, parameter :: mpi_max_info_val = 1023
integer, private, parameter :: mpi_max_library_version_string = 8192-1
integer, private, parameter :: mpi_max_object_name = 127
integer, private, parameter :: mpi_max_port_name = 255
integer, private, parameter :: mpi_max_processor_name = 128-1
integer, private, parameter :: mpi_maxloc = 1476395020
integer, private, parameter :: mpi_message_no_proc = 1811939328
integer, private, parameter :: mpi_message_null = 738197504
integer, private, parameter :: mpi_min = 1476395010
integer, private, parameter :: mpi_minloc = 1476395019
integer, private, parameter :: mpi_mode_append = 128
integer, private, parameter :: mpi_mode_create = 1
integer, private, parameter :: mpi_mode_delete_on_close = 16
integer, private, parameter :: mpi_mode_excl = 64
integer, private, parameter :: mpi_mode_nocheck = 1024
integer, private, parameter :: mpi_mode_noprecede = 8192
integer, private, parameter :: mpi_mode_noput = 4096
integer, private, parameter :: mpi_mode_nostore = 2048
integer, private, parameter :: mpi_mode_nosucceed = 16384
integer, private, parameter :: mpi_mode_rdonly = 2
integer, private, parameter :: mpi_mode_rdwr = 8
integer, private, parameter :: mpi_mode_sequential = 256
integer, private, parameter :: mpi_mode_unique_open = 32
integer, private, parameter :: mpi_mode_wronly = 4
integer, private, parameter :: mpi_no_op = 1476395022
integer, private, parameter :: mpi_offset = 1275070532
integer, private, parameter :: mpi_offset_kind = 8
integer, private, parameter :: mpi_op_null = 402653184
integer, private, parameter :: mpi_order_c = 56
integer, private, parameter :: mpi_order_fortran = 57
integer, private, parameter :: mpi_packed = 1275068687
integer, private, parameter :: mpi_proc_null = -1
integer, private, parameter :: mpi_prod = 1476395012
integer, private, parameter :: mpi_real = 1275069468
integer, private, parameter :: mpi_real16 = 1275072555
integer, private, parameter :: mpi_real4 = 1275069479
integer, private, parameter :: mpi_real8 = 1275070505
integer, private, parameter :: mpi_replace = 1476395021
integer, private, parameter :: mpi_request_null = 738197504
integer, private, parameter :: mpi_root = -3
integer, private, parameter :: mpi_seek_cur = 602
integer, private, parameter :: mpi_seek_end = 604
integer, private, parameter :: mpi_seek_set = 600
integer, private, parameter :: mpi_short = 1275068931
integer, private, parameter :: mpi_short_int = -1946157053
integer, private, parameter :: mpi_signed_char = 1275068696
integer, private, parameter :: mpi_similar = 2
integer, private, parameter :: mpi_source = 3
integer, private, parameter :: mpi_status_size = 5
logical, private, parameter :: mpi_subarrays_supported =  .false. 
integer, private, parameter :: mpi_subversion = 1
integer, private, parameter :: mpi_success = 0
integer, private, parameter :: mpi_sum = 1476395011
integer, private, parameter :: mpi_tag = 4
integer, private, parameter :: mpi_tag_ub = 1681915906
integer, private, parameter :: mpi_thread_funneled = 1
integer, private, parameter :: mpi_thread_multiple = 3
integer, private, parameter :: mpi_thread_serialized = 2
integer, private, parameter :: mpi_thread_single = 0
integer, private, parameter :: mpi_typeclass_complex = 3
integer, private, parameter :: mpi_typeclass_integer = 2
integer, private, parameter :: mpi_typeclass_real = 1
integer, private, parameter :: mpi_ub = 1275068433
integer, private, parameter :: mpi_uint16_t = 1275068988
integer, private, parameter :: mpi_uint32_t = 1275069501
integer, private, parameter :: mpi_uint64_t = 1275070526
integer, private, parameter :: mpi_uint8_t = 1275068731
integer, private, parameter :: mpi_undefined = -32766
integer, private, parameter :: mpi_unequal = 3
integer, private, parameter :: mpi_universe_size = 1681915914
integer, private, parameter :: mpi_unsigned = 1275069446
integer, private, parameter :: mpi_unsigned_char = 1275068674
integer, private, parameter :: mpi_unsigned_long = 1275070472
integer, private, parameter :: mpi_unsigned_long_long = 1275070489
integer, private, parameter :: mpi_unsigned_short = 1275068932
integer, private, parameter :: mpi_version = 3
integer, private, parameter :: mpi_wchar = 1275069454
integer, private, parameter :: mpi_win_base = 1711276034
integer, private, parameter :: mpi_win_create_flavor = 1711276040
integer, private, parameter :: mpi_win_disp_unit = 1711276038
integer, private, parameter :: mpi_win_flavor_allocate = 2
integer, private, parameter :: mpi_win_flavor_create = 1
integer, private, parameter :: mpi_win_flavor_dynamic = 3
integer, private, parameter :: mpi_win_flavor_shared = 4
integer, private, parameter :: mpi_win_model = 1711276042
integer, private, parameter :: mpi_win_null = 536870912
integer, private, parameter :: mpi_win_separate = 1
integer, private, parameter :: mpi_win_size = 1711276036
integer, private, parameter :: mpi_win_unified = 2
integer, private, parameter :: mpi_wtime_is_global = 1681915912
integer, public, parameter :: nmax = 40000
integer, private, parameter :: npx = 2
integer, private, parameter :: npy = 2
integer, private, parameter :: nr = 15
integer, private, parameter :: nsx = 1
integer, private, parameter :: nsy = 1
integer, private, parameter :: null_tile = -1
integer, private, parameter :: snx = 31
integer, private, parameter :: nx = snx*nsx*npx
integer, private, parameter :: sny = 31
integer, private, parameter :: ny = sny*nsy*npy
complex(kind=8), public, parameter :: onecmplx = (0.d0,1.d0)
double precision, private, parameter :: onerl = 1.0d0
double precision, private, parameter :: oners = 1.0d0
integer, private, parameter :: precfloat32 = 32
integer, private, parameter :: precfloat64 = 64
character(len=*), private, parameter :: print_map_xy = 'XY'
character(len=*), private, parameter :: print_map_xz = 'XZ'
character(len=*), private, parameter :: print_map_yz = 'YZ'
character(len=*), private, parameter :: process_header = 'PID.TID'
integer, public, parameter :: prtfile = 61
real(kind=8), public, parameter :: rad2deg = 180.d0/pi
integer, public, parameter :: rayfile = 21
integer, private, parameter :: reverse_simulation = 1
integer, public, parameter :: sbpfile = 50
integer, public, parameter :: shdfile = 25
character(len=*), private, parameter :: squeeze_both = 'B'
character(len=*), private, parameter :: squeeze_left = 'L'
character(len=*), private, parameter :: squeeze_right = 'R'
integer, public, parameter :: sspfile = 40
integer, private, parameter :: tangent_simulation = 2
integer, public, parameter :: trcfile = 39
double precision, private, parameter :: tworl = 2.0d0
double precision, private, parameter :: twors = 2.0d0
real, private, parameter :: unset_float4 = 1.234567e5
double precision, private, parameter :: unset_float8 = 1.234567d5
integer, private, parameter :: unset_i = 123456789
double precision, private, parameter :: unset_rl = 1.234567d5
double precision, private, parameter :: unset_rs = 1.234567d5
double precision, private, parameter :: zerorl = 0.0d0
double precision, private, parameter :: zerors = 0.0d0

!==============================================
! declare derived type definitions
!==============================================
type, public :: rxyz
  real(kind=8) :: r
  real(kind=8) :: x
  real(kind=8) :: y
  real(kind=8) :: z
end type

type, private :: beamstructure
  integer :: nsteps
  integer :: ibeamwindow
  real(kind=8) :: deltas
  real(kind=8) :: epsmultiplier = 1
  real(kind=8) :: rloop
  character(len=1) :: component
  character(len=4) :: type = 'G S '
  character(len=7) :: runtype
  type(rxyz) :: box
end type

type, public :: ray2dpt
  integer :: ntopbnc
  integer :: nbotbnc
  integer :: nturnpt
  real(kind=8) :: x(2)
  real(kind=8) :: t(2)
  real(kind=8) :: p(2)
  real(kind=8) :: q(2)
  real(kind=8) :: h(2)
  real(kind=8) :: c
  real(kind=8) :: amp
  real(kind=8) :: phase
  complex(kind=8) :: tau
end type

type, public :: ray2dpt_tl
  real(kind=8) :: x_tl(2)
  real(kind=8) :: t_tl(2)
  real(kind=8) :: p_tl(2)
  real(kind=8) :: q_tl(2)
  real(kind=8) :: h_tl(2)
  real(kind=8) :: c_tl
  real(kind=8) :: amp_tl
  real(kind=8) :: phase_tl
  complex(kind=8) :: tau_tl
end type

!==============================================
! declare common blocks
!==============================================
integer, private :: eedataunit
integer, private :: errormessageunit
integer, private :: ioerrorcount(max_no_threads)
integer, private :: maxlengthprt1d
integer, private :: modeldataunit
integer, private :: mybxhi(max_no_threads)
integer, private :: mybxlo(max_no_threads)
integer, private :: mybyhi(max_no_threads)
integer, private :: mybylo(max_no_threads)
integer, private :: myprocid
integer, private :: mypx
integer, private :: mypy
integer, private :: myxgloballo
integer, private :: myygloballo
integer, private :: nthreads
integer, private :: ntx
integer, private :: nty
integer, private :: numberofprocs
integer, private :: pidio
integer, private :: scrunit1
integer, private :: scrunit2
integer, private :: standardmessageunit
common /eeparams_i/ errormessageunit, standardmessageunit, maxlengthprt1d, scrunit1, scrunit2, eedataunit, modeldataunit, numberofprocs, pidio, &
&myprocid, mypx, mypy, myxgloballo, myygloballo, nthreads, mybxlo, mybxhi, mybylo, mybyhi, ntx, nty, ioerrorcount

logical, private :: debugmode
logical, private :: eebooterror
logical, private :: eeenderror
logical, private :: fatalerror
logical, private :: printmapincludeszeros
logical, private :: usecoupler
logical, private :: usecubedsphereexchange
logical, private :: usenest2w_child
logical, private :: usenest2w_parent
logical, private :: usenest_child
logical, private :: usenest_parent
logical, private :: useoasis
logical, private :: usesetrlstk
logical, private :: usesigreg
logical, private :: usesinglecpuinput
logical, private :: usesinglecpuio
common /eeparams_l/ eebooterror, eeenderror, fatalerror, debugmode, usesinglecpuio, usesinglecpuinput, printmapincludeszeros, usecubedsphereexchange,&
& usecoupler, usenest_parent, usenest_child, usenest2w_parent, usenest2w_child, useoasis, usesetrlstk, usesigreg

character(len=128), private :: myprocessstr
common /eesupp_c/ myprocessstr

character(len=10), private :: commname(max_num_comm_modes)
common /eesupp_commname/ commname

integer, private :: mypid
integer, private :: nprocs
integer, private :: pide
integer, private :: pidn
integer, private :: pids
integer, private :: pidw
integer, private :: tilebie(nsx,nsy)
integer, private :: tilebin(nsx,nsy)
integer, private :: tilebis(nsx,nsy)
integer, private :: tilebiw(nsx,nsy)
integer, private :: tilebje(nsx,nsy)
integer, private :: tilebjn(nsx,nsy)
integer, private :: tilebjs(nsx,nsy)
integer, private :: tilebjw(nsx,nsy)
integer, private :: tilecommmodee(nsx,nsy)
integer, private :: tilecommmoden(nsx,nsy)
integer, private :: tilecommmodes(nsx,nsy)
integer, private :: tilecommmodew(nsx,nsy)
integer, private :: tileno(nsx,nsy)
integer, private :: tilenoe(nsx,nsy)
integer, private :: tilenon(nsx,nsy)
integer, private :: tilenos(nsx,nsy)
integer, private :: tilenow(nsx,nsy)
integer, private :: tilepide(nsx,nsy)
integer, private :: tilepidn(nsx,nsy)
integer, private :: tilepids(nsx,nsy)
integer, private :: tilepidw(nsx,nsy)
integer, private :: tiletagrecve(nsx,nsy)
integer, private :: tiletagrecvn(nsx,nsy)
integer, private :: tiletagrecvs(nsx,nsy)
integer, private :: tiletagrecvw(nsx,nsy)
integer, private :: tiletagsende(nsx,nsy)
integer, private :: tiletagsendn(nsx,nsy)
integer, private :: tiletagsends(nsx,nsy)
integer, private :: tiletagsendw(nsx,nsy)
common /eesupp_i/ mypid, nprocs, pidw, pide, pidn, pids, tilecommmodew, tilecommmodee, tilecommmoden, tilecommmodes, tileno, tilenow, tilenoe, &
&tilenos, tilenon, tilepidw, tilepide, tilepids, tilepidn, tilebiw, tilebie, tilebis, tilebin, tilebjw, tilebje, tilebjs, tilebjn, tiletagsendw, &
&tiletagsende, tiletagsends, tiletagsendn, tiletagrecvw, tiletagrecve, tiletagrecvs, tiletagrecvn

logical, private :: allmyedgesaresharedmemory(max_no_threads)
logical, private :: notusingxperiodicity
logical, private :: notusingyperiodicity
logical, private :: therror(max_no_threads)
logical, private :: threadiscomplete(max_no_threads)
logical, private :: threadisrunning(max_no_threads)
logical, private :: usingmpi
logical, private :: usingsyncmessages
common /eesupp_l/ therror, threadisrunning, threadiscomplete, allmyedgesaresharedmemory, usingmpi, usingsyncmessages, notusingxperiodicity, &
&notusingyperiodicity

integer, private :: mpicomm
integer, private :: mpimyid
integer, private :: mpinprocs
integer, private :: mpipide
integer, private :: mpipidio
integer, private :: mpipidn
integer, private :: mpipidne
integer, private :: mpipidnw
integer, private :: mpipids
integer, private :: mpipidse
integer, private :: mpipidsw
integer, private :: mpipidw
integer, private :: mpipx
integer, private :: mpipy
integer, private :: mpitage
integer, private :: mpitagn
integer, private :: mpitagne
integer, private :: mpitagnw
integer, private :: mpitags
integer, private :: mpitagse
integer, private :: mpitagsw
integer, private :: mpitagw
integer, private :: mpitypexfaceblock_xy_r4
integer, private :: mpitypexfaceblock_xy_r8
integer, private :: mpitypexfaceblock_xyz_r4
integer, private :: mpitypexfaceblock_xyz_r8
integer, private :: mpitypexfacethread_xy_r4(max_no_threads)
integer, private :: mpitypexfacethread_xy_r8(max_no_threads)
integer, private :: mpitypexfacethread_xyz_r4(max_no_threads)
integer, private :: mpitypexfacethread_xyz_r8(max_no_threads)
integer, private :: mpitypeyfaceblock_xy_r4
integer, private :: mpitypeyfaceblock_xy_r8
integer, private :: mpitypeyfaceblock_xyz_r4
integer, private :: mpitypeyfaceblock_xyz_r8
integer, private :: mpitypeyfacethread_xy_r4(max_no_threads)
integer, private :: mpitypeyfacethread_xy_r8(max_no_threads)
integer, private :: mpitypeyfacethread_xyz_r4(max_no_threads)
integer, private :: mpitypeyfacethread_xyz_r8(max_no_threads)
integer, private :: mpixgloballo
integer, private :: mpiygloballo
common /eesupp_mpi_i/ mpipidw, mpipide, mpipids, mpipidn, mpipidse, mpipidsw, mpipidne, mpipidnw, mpipidio, mpimyid, mpinprocs, mpicomm, mpipx, &
&mpipy, mpixgloballo, mpiygloballo, mpitypexfaceblock_xy_r4, mpitypexfaceblock_xy_r8, mpitypeyfaceblock_xy_r4, mpitypeyfaceblock_xy_r8, &
&mpitypexfaceblock_xyz_r4, mpitypexfaceblock_xyz_r8, mpitypeyfaceblock_xyz_r4, mpitypeyfaceblock_xyz_r8, mpitypexfacethread_xy_r4, &
&mpitypexfacethread_xy_r8, mpitypeyfacethread_xy_r4, mpitypeyfacethread_xy_r8, mpitypexfacethread_xyz_r4, mpitypexfacethread_xyz_r8, &
&mpitypeyfacethread_xyz_r4, mpitypeyfacethread_xyz_r8, mpitage, mpitagw, mpitagn, mpitags, mpitagse, mpitagsw, mpitagnw, mpitagne

integer, private :: mpi_comm_model
common /mpi_comms/ mpi_comm_model

integer, private :: mpi_myxgloballo(npx*npy)
integer, private :: mpi_myygloballo(npx*npy)
common /mpi_fullmap_i/ mpi_myxgloballo, mpi_myygloballo

integer, private :: mpi_unweighted
common /mpifcmb5/ mpi_unweighted

integer, private :: mpi_weights_empty
common /mpifcmb9/ mpi_weights_empty

integer, private :: mpi_bottom
integer, private :: mpi_in_place
integer, private :: mpi_status_ignore(mpi_status_size)
common /mpipriv1/ mpi_bottom, mpi_in_place, mpi_status_ignore

integer, private :: mpi_errcodes_ignore(1)
integer, private :: mpi_statuses_ignore(mpi_status_size,1)
common /mpipriv2/ mpi_statuses_ignore, mpi_errcodes_ignore

character(len=1), private :: mpi_argv_null(1)
character(len=1), private :: mpi_argvs_null(1,1)
common /mpiprivc/ mpi_argvs_null, mpi_argv_null

double precision, private :: heatcapacity_cp
common /parm_a/ heatcapacity_cp

double precision, private :: atm_cp
double precision, private :: atm_kappa
double precision, private :: atm_po
double precision, private :: atm_rd
double precision, private :: atm_rq
double precision, private :: celsius2k
integer, private :: integr_geopot
integer, private :: selectfindrosurf
common /parm_atm/ celsius2k, atm_cp, atm_rd, atm_kappa, atm_rq, atm_po, integr_geopot, selectfindrosurf

character(len=max_len_fnam), private :: addmassfile
character(len=max_len_fnam), private :: addswallfile
character(len=max_len_fnam), private :: addwwallfile
character(len=max_len_fnam), private :: adtapedir
character(len=max_len_fnam), private :: bathyfile
character(len=max_len_fnam), private :: buoyancyrelation
character(len=max_len_fnam), private :: delrcfile
character(len=max_len_fnam), private :: delrfile
character(len=max_len_fnam), private :: delxfile
character(len=max_len_fnam), private :: delyfile
character(len=max_len_fnam), private :: diffkrfile
character(len=max_len_fnam), private :: eddypsixfile
character(len=max_len_fnam), private :: eddypsiyfile
character(len=max_len_fnam), private :: empmrfile
character(len=6), private :: eostype
character(len=max_len_fnam), private :: geopotanomfile
character(len=max_len_fnam), private :: geothermalfile
character(len=max_len_fnam), private :: gravityfile
character(len=max_len_fnam), private :: horizgridfile
character(len=max_len_fnam), private :: hybsigmfile
character(len=max_len_fnam), private :: hydrogsaltfile
character(len=max_len_fnam), private :: hydrogthetafile
character(len=max_len_fnam), private :: lambdasaltfile
character(len=max_len_fnam), private :: lambdathetafile
character(len=max_len_fnam), private :: mdsiolocaldir
character(len=max_len_fnam), private :: meridwindfile
character(len=10), private :: pickupsuff
character(len=max_len_fnam), private :: ploadfile
character(len=max_len_fnam), private :: psurfinitfile
character(len=max_len_fnam), private :: rhoreffile
character(len=max_len_fnam), private :: saltclimfile
character(len=max_len_fnam), private :: saltfluxfile
character(len=max_len_fnam), private :: sreffile
character(len=max_len_fnam), private :: surfqfile
character(len=max_len_fnam), private :: surfqnetfile
character(len=max_len_fnam), private :: surfqswfile
character(len=max_len_prec/2), private :: the_run_name
character(len=max_len_fnam), private :: thetaclimfile
character(len=max_len_fnam), private :: topofile
character(len=max_len_fnam), private :: treffile
character(len=max_len_fnam), private :: uvelinitfile
character(len=max_len_fnam), private :: visca4dfile
character(len=max_len_fnam), private :: visca4zfile
character(len=max_len_fnam), private :: viscahdfile
character(len=max_len_fnam), private :: viscahzfile
character(len=max_len_fnam), private :: vvelinitfile
character(len=max_len_fnam), private :: wghtbalancefile
character(len=max_len_fnam), private :: zonalwindfile
common /parm_c/ buoyancyrelation, eostype, pickupsuff, mdsiolocaldir, adtapedir, treffile, sreffile, rhoreffile, gravityfile, delrfile, delrcfile, &
&hybsigmfile, delxfile, delyfile, horizgridfile, bathyfile, topofile, addwwallfile, addswallfile, viscahdfile, viscahzfile, visca4dfile, visca4zfile,&
& hydrogthetafile, hydrogsaltfile, diffkrfile, zonalwindfile, meridwindfile, thetaclimfile, saltclimfile, empmrfile, saltfluxfile, surfqfile, &
&surfqnetfile, surfqswfile, uvelinitfile, vvelinitfile, psurfinitfile, ploadfile, geopotanomfile, addmassfile, eddypsixfile, eddypsiyfile, &
&geothermalfile, lambdathetafile, lambdasaltfile, wghtbalancefile, the_run_name

integer, private :: cg2dmaxiters
integer, private :: cg2dminitersnsa
integer, private :: cg2dprecondfreq
integer, private :: cg2duseminressol
integer, private :: cg3dmaxiters
integer, private :: debuglevel
integer, private :: momforcingoutab
integer, private :: monitorselect
integer, private :: nenditer
integer, private :: niter0
integer, private :: nonlinfreesurf
integer, private :: ntimesteps
integer, private :: ntimesteps_l2
integer, private :: pcellmix_select
integer, private :: plotlevel
integer, private :: printresidualfreq
integer, private :: readbinaryprec
integer, private :: rwsuffixtype
integer, private :: saltadvscheme
integer, private :: saltvertadvscheme
integer, private :: select3dcorischeme
integer, private :: select_rstar
integer, private :: selectaddfluid
integer, private :: selectbalanceempmr
integer, private :: selectbotdragquadr
integer, private :: selectcorimap
integer, private :: selectcorischeme
integer, private :: selectimplicitdrag
integer, private :: selectkescheme
integer, private :: selectmetricterms
integer, private :: selectnhfreesurf
integer, private :: selectp_ineos_zc
integer, private :: selectpenetratingsw
integer, private :: selectsigmacoord
integer, private :: selectvortscheme
integer, private :: tempadvscheme
integer, private :: tempvertadvscheme
integer, private :: tracforcingoutab
integer, private :: writebinaryprec
common /parm_i/ cg2dmaxiters, cg2dminitersnsa, cg2dprecondfreq, cg2duseminressol, cg3dmaxiters, printresidualfreq, niter0, ntimesteps, ntimesteps_l2,&
& nenditer, selectcorimap, selectsigmacoord, nonlinfreesurf, select_rstar, selectnhfreesurf, selectp_ineos_zc, selectaddfluid, selectbalanceempmr, &
&selectimplicitdrag, momforcingoutab, tracforcingoutab, tempadvscheme, tempvertadvscheme, saltadvscheme, saltvertadvscheme, selectkescheme, &
&selectvortscheme, selectmetricterms, selectcorischeme, select3dcorischeme, selectbotdragquadr, selectpenetratingsw, pcellmix_select, readbinaryprec,&
& writebinaryprec, rwsuffixtype, monitorselect, debuglevel, plotlevel

logical, private :: addfrictionheating
logical, private :: allowfreezing
logical, private :: applyexchuv_early
logical, private :: balanceprintmean
logical, private :: balanceqnet
logical, private :: balancesaltclimrelax
logical, private :: balancethetaclimrelax
logical, private :: bottomvisc_pcell
logical, private :: calc_wvelocity
logical, private :: checkinisalt
logical, private :: checkinitemp
logical, private :: deepatmosphere
logical, private :: doab_ongtgs
logical, private :: doresethfactors
logical, private :: dosaltclimrelax
logical, private :: dothetaclimrelax
logical, private :: dumpinitandlast
logical, private :: exactconserv
logical, private :: fluidisair
logical, private :: fluidiswater
logical, private :: globalfiles
logical, private :: haswetcscorners
logical, private :: highordervorticity
logical, private :: implicitdiffusion
logical, private :: implicitfreesurface
logical, private :: implicitintgravwave
logical, private :: implicitviscosity
logical, private :: interdiffkr_pcell
logical, private :: interviscar_pcell
logical, private :: linfsconservetr
logical, private :: maskinisalt
logical, private :: maskinitemp
logical, private :: momadvection
logical, private :: momdissip_in_ab
logical, private :: momforcing
logical, private :: momimplvertadv
logical, private :: mompressureforcing
logical, private :: momstepping
logical, private :: momtidalforcing
logical, private :: momviscosity
logical, private :: monitor_stdio
logical, private :: multidimadvection
logical, private :: no_slip_bottom
logical, private :: no_slip_sides
logical, private :: nonhydrostatic
logical, private :: outputtypesinclusive
logical, private :: periodicexternalforcing
logical, private :: pickup_read_mdsio
logical, private :: pickup_write_immed
logical, private :: pickup_write_mdsio
logical, private :: pickupstrictlymatch
logical, private :: quasihydrostatic
logical, private :: rigidlid
logical, private :: rotategrid
logical, private :: salt_staypositive
logical, private :: saltadvection
logical, private :: saltforcing
logical, private :: saltimplvertadv
logical, private :: saltisactivetr
logical, private :: saltstepping
logical, private :: saltvertdiff4
logical, private :: setcenterdr
logical, private :: setinterfdr
logical, private :: snapshot_mdsio
logical, private :: staggertimestep
logical, private :: startfrompickupab2
logical, private :: storephihyd4phys
logical, private :: temp_staypositive
logical, private :: tempadvection
logical, private :: tempforcing
logical, private :: tempimplvertadv
logical, private :: tempisactivetr
logical, private :: tempstepping
logical, private :: tempvertdiff4
logical, private :: timeave_mdsio
logical, private :: uniformfreesurflev
logical, private :: uniformlin_phisurf
logical, private :: upwindshear
logical, private :: upwindvorticity
logical, private :: use3dsolver
logical, private :: useabsvorticity
logical, private :: useareavisclength
logical, private :: usecdscheme
logical, private :: usecoriolis
logical, private :: usefullleith
logical, private :: usejamartmomadv
logical, private :: usemin4hfacedges
logical, private :: usemultidimadvec
logical, private :: usenhmterms
logical, private :: usensacgsolver
logical, private :: usepickupbeforec54
logical, private :: userealfreshwaterflux
logical, private :: usesmag3d
logical, private :: usesrcgsolver
logical, private :: usestraintensionvisc
logical, private :: usingcartesiangrid
logical, private :: usingcurvilineargrid
logical, private :: usingcylindricalgrid
logical, private :: usingpcoords
logical, private :: usingsphericalpolargrid
logical, private :: usingzcoords
logical, private :: vectorinvariantmomentum
logical, private :: writepickupatend
common /parm_l/ fluidisair, fluidiswater, usingpcoords, usingzcoords, usingcartesiangrid, usingsphericalpolargrid, rotategrid, usingcylindricalgrid, &
&usingcurvilineargrid, haswetcscorners, deepatmosphere, setinterfdr, setcenterdr, usemin4hfacedges, interviscar_pcell, interdiffkr_pcell, &
&no_slip_sides, no_slip_bottom, bottomvisc_pcell, usesmag3d, usefullleith, usestraintensionvisc, useareavisclength, momviscosity, momadvection, &
&momforcing, momtidalforcing, mompressureforcing, usenhmterms, usecoriolis, usecdscheme, vectorinvariantmomentum, usejamartmomadv, upwindvorticity, &
&highordervorticity, useabsvorticity, upwindshear, momstepping, calc_wvelocity, tempstepping, saltstepping, addfrictionheating, temp_staypositive, &
&salt_staypositive, tempadvection, tempvertdiff4, tempisactivetr, tempforcing, saltadvection, saltvertdiff4, saltisactivetr, saltforcing, &
&maskinitemp, maskinisalt, checkinitemp, checkinisalt, usensacgsolver, usesrcgsolver, rigidlid, implicitfreesurface, uniformlin_phisurf, &
&uniformfreesurflev, exactconserv, linfsconservetr, userealfreshwaterflux, storephihyd4phys, quasihydrostatic, nonhydrostatic, use3dsolver, &
&implicitintgravwave, staggertimestep, applyexchuv_early, doresethfactors, implicitdiffusion, implicitviscosity, tempimplvertadv, saltimplvertadv, &
&momimplvertadv, multidimadvection, usemultidimadvec, momdissip_in_ab, doab_ongtgs, balanceqnet, balanceprintmean, balancethetaclimrelax, &
&balancesaltclimrelax, dothetaclimrelax, dosaltclimrelax, allowfreezing, periodicexternalforcing, globalfiles, pickupstrictlymatch, &
&usepickupbeforec54, startfrompickupab2, pickup_read_mdsio, pickup_write_mdsio, pickup_write_immed, writepickupatend, timeave_mdsio, snapshot_mdsio, &
&monitor_stdio, outputtypesinclusive, dumpinitandlast

logical, private :: useaim
logical, private :: useatm2d
logical, private :: useatm_phys
logical, private :: useautodiff
logical, private :: usebbl
logical, private :: usebulkforce
logical, private :: usecal
logical, private :: usecheapaml
logical, private :: usectrl
logical, private :: usediagnostics
logical, private :: usedown_slope
logical, private :: useebm
logical, private :: useecco
logical, private :: useembed_files
logical, private :: useexf
logical, private :: usefizhi
logical, private :: useflt
logical, private :: usefrazil
logical, private :: usegad
logical, private :: usegchem
logical, private :: useggl90
logical, private :: usegmredi
logical, private :: usegrdchk
logical, private :: usegridalt
logical, private :: useicefront
logical, private :: useihop
logical, private :: usekl10
logical, private :: usekpp
logical, private :: useland
logical, private :: uselayers
logical, private :: usematrix
logical, private :: usemnc
logical, private :: usemy82
logical, private :: usemypackage
logical, private :: useobcs
logical, private :: useoffline
logical, private :: useopps
logical, private :: usepp81
logical, private :: useprofiles
logical, private :: useptracers
logical, private :: userbcs
logical, private :: useregrid
logical, private :: userunclock
logical, private :: usesalt_plume
logical, private :: usesbo
logical, private :: useseaice
logical, private :: useshap_filt
logical, private :: useshelfice
logical, private :: usesmooth
logical, private :: usestic
logical, private :: usestreamice
logical, private :: usethsice
logical, private :: usezonal_filt
common /parm_packages/ usegad, useobcs, useshap_filt, usezonal_filt, useopps, usepp81, usekl10, usemy82, useggl90, usekpp, usegmredi, usebbl, &
&usedown_slope, usecal, useexf, usebulkforce, useebm, usecheapaml, usegrdchk, usesmooth, useprofiles, useecco, usectrl, usesbo, useflt, useautodiff, &
&useptracers, usegchem, userbcs, useoffline, usematrix, usefrazil, useseaice, usesalt_plume, useshelfice, usestic, usestreamice, useicefront, &
&usethsice, useland, useatm2d, useaim, useatm_phys, usefizhi, usegridalt, usediagnostics, useregrid, uselayers, usemnc, userunclock, useembed_files, &
&usemypackage, useihop

double precision, private :: abeps
double precision, private :: adjdumpfreq
double precision, private :: adjmonitorfreq
double precision, private :: affacmom
double precision, private :: alph_ab
double precision, private :: basetime
double precision, private :: beta
double precision, private :: beta_ab
double precision, private :: bl79latvary
double precision, private :: bottomdraglinear
double precision, private :: bottomdragquadratic
double precision, private :: cadjfreq
double precision, private :: cffacmom
double precision, private :: cg2dpcoffdfac
double precision, private :: cg2dtargetresidual
double precision, private :: cg2dtargetreswunit
double precision, private :: cg3dtargetresidual
double precision, private :: cg3dtargetreswunit
double precision, private :: chkptfreq
double precision, private :: convertfw2salt
double precision, private :: cospower
double precision, private :: dbdrref(nr)
double precision, private :: delr(nr)
double precision, private :: delrc(nr+1)
double precision, private :: deltat
double precision, private :: deltatclock
double precision, private :: deltatfreesurf
double precision, private :: deltatmom
double precision, private :: diagfreq
double precision, private :: diffk4s
double precision, private :: diffk4t
double precision, private :: diffkhs
double precision, private :: diffkht
double precision, private :: diffkr4s(nr)
double precision, private :: diffkr4t(nr)
double precision, private :: diffkrbl79deep
double precision, private :: diffkrbl79ho
double precision, private :: diffkrbl79scl
double precision, private :: diffkrbl79surf
double precision, private :: diffkrbleqdeep
double precision, private :: diffkrbleqho
double precision, private :: diffkrbleqscl
double precision, private :: diffkrbleqsurf
double precision, private :: diffkrnrs(nr)
double precision, private :: diffkrnrt(nr)
double precision, private :: drhosmall
double precision, private :: dttracerlev(nr)
double precision, private :: dumpfreq
double precision, private :: endtime
double precision, private :: epsab_cd
double precision, private :: externforcingcycle
double precision, private :: externforcingperiod
double precision, private :: f0
double precision, private :: fofacmom
double precision, private :: fprime
double precision, private :: freesurffac
double precision, private :: gbaro
double precision, private :: gravfacc(nr)
double precision, private :: gravfacf(nr+1)
double precision, private :: gravity
double precision, private :: hfacinf
double precision, private :: hfacmin
double precision, private :: hfacmindp
double precision, private :: hfacmindr
double precision, private :: hfacmindz
double precision, private :: hfacsup
double precision, private :: hmixcriteria
double precision, private :: hmixsmooth
double precision, private :: implicdiv2dflow
double precision, private :: implicitnhpress
double precision, private :: implicsurfpress
double precision, private :: ivdc_kappa
double precision, private :: latbandclimrelax
double precision, private :: mass2runit
double precision, private :: monitorfreq
double precision, private :: mtfacmom
double precision, private :: nh_am2
double precision, private :: omega
double precision, private :: pcellmix_delr
double precision, private :: pcellmix_diffkr(nr)
double precision, private :: pcellmix_maxfac
double precision, private :: pcellmix_viscar(nr)
double precision, private :: pchkptfreq
double precision, private :: pffacmom
double precision, private :: phieuler
double precision, private :: phiref(2*nr+1)
double precision, private :: pref4eos(nr)
double precision, private :: psieuler
double precision, private :: radius_fromhorizgrid
double precision, private :: rcd
double precision, private :: recip_gravfacc(nr)
double precision, private :: recip_gravfacf(nr+1)
double precision, private :: recip_gravity
double precision, private :: recip_rhoconst
double precision, private :: recip_rhofacc(nr)
double precision, private :: recip_rhofacf(nr+1)
double precision, private :: recip_rsphere
double precision, private :: rho1ref(nr)
double precision, private :: rhoconst
double precision, private :: rhoconstfresh
double precision, private :: rhofacc(nr)
double precision, private :: rhofacf(nr+1)
double precision, private :: rhonil
double precision, private :: rhoref(nr)
double precision, private :: rotationperiod
double precision, private :: rsigmabnd
double precision, private :: rsphere
double precision, private :: runit2mass
double precision, private :: runit2z(nr)
double precision, private :: rvel2wunit(nr+1)
double precision, private :: salt_addmass
double precision, private :: salt_evprrn
double precision, private :: sealev_z
double precision, private :: siceloadfac
double precision, private :: sidedragfactor
double precision, private :: smag3d_coeff
double precision, private :: smag3d_diffcoeff
double precision, private :: smoothabsfuncrange
double precision, private :: sref(nr)
double precision, private :: starttime
double precision, private :: surf_pref
double precision, private :: taucd
double precision, private :: tausaltclimrelax
double precision, private :: tauthetaclimrelax
double precision, private :: tave_lastiter
double precision, private :: tavefreq
double precision, private :: tcylin
double precision, private :: tcylout
double precision, private :: temp_addmass
double precision, private :: temp_evprrn
double precision, private :: thetaconst
double precision, private :: thetaeuler
double precision, private :: top_pres
double precision, private :: tref(nr)
double precision, private :: vffacmom
double precision, private :: visca4
double precision, private :: visca4d
double precision, private :: visca4grid
double precision, private :: visca4gridmax
double precision, private :: visca4gridmin
double precision, private :: visca4max
double precision, private :: visca4remax
double precision, private :: visca4w
double precision, private :: visca4z
double precision, private :: viscah
double precision, private :: viscahd
double precision, private :: viscahgrid
double precision, private :: viscahgridmax
double precision, private :: viscahgridmin
double precision, private :: viscahmax
double precision, private :: viscahremax
double precision, private :: viscahw
double precision, private :: viscahz
double precision, private :: viscarnr(nr)
double precision, private :: viscc2leith
double precision, private :: viscc2leithd
double precision, private :: viscc2leithqg
double precision, private :: viscc2smag
double precision, private :: viscc4leith
double precision, private :: viscc4leithd
double precision, private :: viscc4smag
double precision, private :: viscfacadj
double precision, private :: wunit2rvel(nr+1)
double precision, private :: xgorigin
double precision, private :: ygorigin
double precision, private :: z2runit(nr)
double precision, private :: zroughbot
common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, xgorigin, ygorigin, &
&rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, dttracerlev, deltatfreesurf, deltatclock, abeps, &
&alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, &
&viscahgridmax, viscahgridmin, viscc2leith, viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w,&
& visca4max, visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, diffkrnrt, &
&diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, bl79latvary, diffkrbleqsurf, &
&diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, &
&implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, &
&gravfacf, recip_gravfacf, rhonil, rhoconst, recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, &
&tref, sref, rhoref, dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, &
&endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, affacmom, vffacmom, pffacmom,&
& cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, latbandclimrelax, externforcingcycle, externforcingperiod, &
&convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, &
&sidedragfactor, bottomdraglinear, bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, &
&psieuler

!==============================================
! declare local variables
!==============================================
real(kind=8), public :: afreq
integer, public :: ismallstepctr = 0
integer, public :: istep
integer, public :: nrz_per_range
real(kind=8), private :: srcazimangle
real(kind=8), public :: srcdeclangle
character(len=80), public :: title

!==============================================
! declare derived type variables
!==============================================
type(beamstructure), public :: beam
type(ray2dpt), public :: ray2d(nmax)
type(ray2dpt_tl), public :: ray2d_tl(nmax)

!==============================================
! declare external procedures and functions
!==============================================
external :: mpi_comm_dup_fn
private :: mpi_comm_dup_fn
external :: mpi_comm_null_copy_fn
private :: mpi_comm_null_copy_fn
external :: mpi_comm_null_delete_fn
private :: mpi_comm_null_delete_fn
external :: mpi_conversion_fn_null
private :: mpi_conversion_fn_null
external :: mpi_dup_fn
private :: mpi_dup_fn
external :: mpi_null_copy_fn
private :: mpi_null_copy_fn
external :: mpi_null_delete_fn
private :: mpi_null_delete_fn
external :: mpi_type_dup_fn
private :: mpi_type_dup_fn
external :: mpi_type_null_copy_fn
private :: mpi_type_null_copy_fn
external :: mpi_type_null_delete_fn
private :: mpi_type_null_delete_fn
external :: mpi_win_dup_fn
private :: mpi_win_dup_fn
external :: mpi_win_null_copy_fn
private :: mpi_win_null_copy_fn
external :: mpi_win_null_delete_fn
private :: mpi_win_null_delete_fn
double precision, external :: mpi_wtick
private :: mpi_wtick
double precision, external :: mpi_wtime
private :: mpi_wtime
double precision, external :: pmpi_wtick
private :: pmpi_wtick
double precision, external :: pmpi_wtime
private :: pmpi_wtime

contains
  subroutine bcastray( root, comm )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
  implicit none

!==============================================
! declare arguments
!==============================================
  integer, intent(in) :: comm
  integer, intent(in) :: root

!==============================================
! declare local variables
!==============================================
  integer :: ierr
  integer :: mpi_ihop_ray2d = mpi_datatype_null
  logical :: ray2d_type_committed =  .false. 

  if (mpi_ihop_ray2d == mpi_datatype_null) then
    call ray2dpttypeinit( ray2d(1),ray2d(2),mpi_ihop_ray2d,ray2d_type_committed )
  endif
  call mpi_bcast( beam%nsteps,1,mpi_integer,root,comm,ierr )
  call mpi_bcast( ray2d,nmax,mpi_ihop_ray2d,root,comm,ierr )
  end subroutine bcastray
  subroutine bcastray_tl( root, comm )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
  implicit none

!==============================================
! declare arguments
!==============================================
  integer, intent(in) :: comm
  integer, intent(in) :: root

!==============================================
! declare local variables
!==============================================
  integer :: ierr
  integer :: mpi_ihop_ray2d = mpi_datatype_null
  integer :: mpi_ihop_ray2dh
  logical :: ray2d_type_committed =  .false. 

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
  if (mpi_ihop_ray2d == mpi_datatype_null) then
    call ray2dpttypeinit_tl( ray2d(1),ray2d_tl(1),ray2d(2),ray2d_tl(2),mpi_ihop_ray2d,ray2d_type_committed )
  endif
  call mpi_bcast( beam%nsteps,1,mpi_integer,root,comm,ierr )
  mpi_ihop_ray2dh = 0
  call mpi_bcast( ray2d_tl,nmax,mpi_ihop_ray2dh,root,comm,ierr )
  call mpi_bcast( ray2d,nmax,mpi_ihop_ray2d,root,comm,ierr )

  end subroutine bcastray_tl
  subroutine free_ihop_ray2d( mythid )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
  implicit none

!==============================================
! declare arguments
!==============================================
  integer, intent(in) :: mythid

! removed label 99999
  end subroutine free_ihop_ray2d
  subroutine ray2dpttypeinit( singleray2d, nextray2d, mytype, type_committed )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
  implicit none

!==============================================
! declare parameters
!==============================================
  integer, parameter :: typesize = 3

!==============================================
! declare arguments
!==============================================
  integer, intent(inout) :: mytype
  type(ray2dpt), intent(in) :: nextray2d
  type(ray2dpt), intent(in) :: singleray2d
  logical, intent(inout) :: type_committed

!==============================================
! declare local variables
!==============================================
  integer(kind=mpi_address_kind) :: a1
  integer(kind=mpi_address_kind) :: a2
  integer(kind=mpi_address_kind) :: addr(typesize)
  integer(kind=mpi_address_kind) :: base
  integer :: bl(typesize)
  integer(kind=mpi_address_kind) :: disp(typesize)
  integer(kind=mpi_address_kind) :: extent
  integer :: ierr
  integer :: mpi_cl
  integer :: mpi_rl
  integer :: n
  integer :: tmptype
  integer :: ty(typesize)

  if ( .not. type_committed) then
    if (storage_size(real(singleray2d%tau)) == 64) then
      mpi_cl = mpi_double_complex
      mpi_rl = mpi_double_precision
    else
      mpi_cl = mpi_complex
      mpi_rl = mpi_real
    endif
    bl = 1
    call mpi_get_address( singleray2d,base,ierr )
    n = 1
    call mpi_get_address( singleray2d%x(1),addr(n),ierr )
    bl(n) = 2
    disp(n) = addr(n)-base
    ty(n) = mpi_rl
    n = n+1
    call mpi_get_address( singleray2d%q(1),addr(n),ierr )
    bl(n) = 2
    disp(n) = addr(n)-base
    ty(n) = mpi_rl
    n = n+1
    call mpi_get_address( singleray2d%tau,addr(n),ierr )
    disp(n) = addr(n)-base
    ty(n) = mpi_cl
    call mpi_type_create_struct( n,bl,disp,ty,tmptype,ierr )
    call mpi_get_address( singleray2d,a1,ierr )
    call mpi_get_address( nextray2d,a2,ierr )
    extent = a2-a1
    call mpi_type_create_resized( tmptype,0_mpi_address_kind,extent,mytype,ierr )
    call mpi_type_commit( mytype,ierr )
    call mpi_type_free( tmptype,ierr )
    type_committed =  .true. 
  endif
  end subroutine ray2dpttypeinit
  subroutine ray2dpttypeinit_tl( singleray2d, singleray2d_tl, nextray2d, nextray2d_tl, mytype, type_committed )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
!******************************************************************
!******************************************************************
  implicit none

!==============================================
! declare parameters
!==============================================
  integer, parameter :: typesize = 3

!==============================================
! declare arguments
!==============================================
  integer, intent(in) :: mytype
  type(ray2dpt), intent(in) :: nextray2d
  type(ray2dpt_tl), intent(in) :: nextray2d_tl
  type(ray2dpt), intent(in) :: singleray2d
  type(ray2dpt_tl), intent(in) :: singleray2d_tl
  logical, intent(inout) :: type_committed

!==============================================
! declare local variables
!==============================================
  integer(kind=mpi_address_kind) :: a1
  integer(kind=mpi_address_kind) :: a2
  integer(kind=mpi_address_kind) :: addr(typesize)
  integer(kind=mpi_address_kind) :: base
  integer :: bl(typesize)
  integer(kind=mpi_address_kind) :: disp(typesize)
  integer(kind=mpi_address_kind) :: extent
  integer :: ierr
  integer :: mpi_cl
  integer :: mpi_rl
  integer :: n
  integer :: tmptype
  integer :: ty(typesize)

!----------------------------------------------
! TANGENT LINEAR AND FUNCTION STATEMENTS
!----------------------------------------------
  if ( .not. type_committed) then
    if (storage_size(real(singleray2d%tau)) == 64) then
      mpi_cl = mpi_double_complex
      mpi_rl = mpi_double_precision
    else
      mpi_cl = mpi_complex
      mpi_rl = mpi_real
    endif
    bl = 1
    call mpi_get_address( singleray2d,base,ierr )
    n = 1
    call mpi_get_address( singleray2d%x(1),addr(n),ierr )
    bl(n) = 2
    disp(n) = addr(n)-base
    ty(n) = mpi_rl
    n = n+1
    call mpi_get_address( singleray2d%q(1),addr(n),ierr )
    bl(n) = 2
    disp(n) = addr(n)-base
    ty(n) = mpi_rl
    n = n+1
    call mpi_get_address( singleray2d%tau,addr(n),ierr )
    disp(n) = addr(n)-base
    ty(n) = mpi_cl
    call mpi_type_create_struct( n,bl,disp,ty,tmptype,ierr )
    call mpi_get_address( singleray2d,a1,ierr )
    call mpi_get_address( nextray2d,a2,ierr )
    extent = a2-a1
    call mpi_type_create_resized( tmptype,0_mpi_address_kind,extent,mytype,ierr )
    call mpi_type_commit( mytype,ierr )
    call mpi_type_free( tmptype,ierr )
    type_committed =  .true. 
  endif

  end subroutine ray2dpttypeinit_tl
end module     ihop_mod
