#ifndef AUTODIFF_OPTIONS_H
#define AUTODIFF_OPTIONS_H
#include "PACKAGES_CONFIG.h"
#include "CPP_OPTIONS.h"

!BOP
! !ROUTINE: AUTODIFF_OPTIONS.h
! !INTERFACE:
! #include "AUTODIFF_OPTIONS.h"

! !DESCRIPTION:
! *==================================================================*
! | CPP options file for AutoDiff (autodiff) package:
! | Control which optional features to compile in this package code.
! *==================================================================*
!EOP

#ifdef ALLOW_AUTODIFF
#ifdef ECCO_CPPOPTIONS_H

!-- When multi-package option-file ECCO_CPPOPTIONS.h is used (directly included
!    in CPP_OPTIONS.h), this option file is left empty since all options that
!   are specific to this package are assumed to be set in ECCO_CPPOPTIONS.h

#else /* ndef ECCO_CPPOPTIONS_H */
!   ==================================================================
!-- Package-specific Options & Macros go here

! o Include/exclude code in order to automatically differentiate MITgcm code
!   using TAF (Transformation of Algorithms in Fortran, http://www.FastOpt.de)
!   or using TAMC (Tangent Linear & Adjoint Model Compiler, needs both defined):
#define ALLOW_AUTODIFF_TAMC
#undef AUTODIFF_TAMC_COMPATIBILITY

!       >>> Checkpointing as handled by TAMC
#define ALLOW_TAMC_CHECKPOINTING

!       >>> Extract adjoint state
#define ALLOW_AUTODIFF_MONITOR
!       >>> and DYNVARS_DIAG adjoint state
#undef ALLOW_AUTODIFF_MONITOR_DIAG

!       >>> DO 2-level checkpointing instead of 3-level
#define AUTODIFF_2_LEVEL_CHECKPOINT

! extend to 4-level checkpointing
#undef AUTODIFF_4_LEVEL_CHECKPOINT

! o use divided adjoint to split adjoint computations
#undef ALLOW_DIVIDED_ADJOINT

! o This flag is incredibly useful as it reduces the number of
!   tape-files on the disc. Maybe it should even be the default.
#define ALLOW_AUTODIFF_WHTAPEIO
!   and related to above:
#undef ALLOW_INIT_WHTAPEIO

! o use standard MDSFINDUINTS instead of local pkg/autodiff version for
!   WHTAPEIO code I/O.
!   Note: comment out the #define below (instead of having an #undef) to
!   enable to set this Option in CPP command line (from the optfile)
!#define AUTODIFF_USE_MDSFINDUNITS

! o use the deprecated autodiff_store/restore method where multiple fields
!   are collected in a single buffer field array before storing to tape.
!   This functionality has been replaced by WHTAPEIO method (see above).
!   Might still be used for OBCS since WHTAPEIO does not support OBCS fields.
#undef AUTODIFF_USE_STORE_RESTORE
#undef AUTODIFF_USE_STORE_RESTORE_OBCS

! o allow using viscFacInAd to recompute viscosities in AD
#define AUTODIFF_ALLOW_VISCFACADJ

! o To remove part of MOM_CALC_VISC (better name would be: MOM_DISABLE_*)
#undef AUTODIFF_DISABLE_LEITH
#undef AUTODIFF_DISABLE_REYNOLDS_SCALE

! o for output of AD-variables (ALLOW_AUTODIFF_MONITOR), specific code (e.g.,
!   in addummy_in_stepping.F) relies on adexch_uv_xy_rs and adexch_xy_rs S/R
!   which might not always be generated by TAF (e.g., when controls do not
!   include any 2D forcing field). In those cases, defining this cpp-option
!   allows to circumvent this missing code issue.
#undef AUTODIFF_EXCLUDE_ADEXCH_RS

!   ==================================================================
#endif /* ndef ECCO_CPPOPTIONS_H */
#endif /* ALLOW_AUTODIFF */
#endif /* AUTODIFF_OPTIONS_H */
