#!/bin/bash
# Options needed for hybrid genmake AD

if [ "$FC" = "gfortran" ]; then
    FFLAGS="$FFLAGS -ffixed-line-length-132"
    F90FLAGS="$F90FLAGS -ffree-line-length-0"
else # FC is ifort
    FFLAGS="$FFLAGS -132"
fi

TAF_FORTRAN_VERS='F95'
TAF_COMMON_FLAGS="-e $TAF_COMMON_FLAGS"
