#!/bin/bash
# Options needed for hybrid genmake AD

if [ "$FC" = "gfortran" ]; then
    FFLAGS="$FFLAGS -ffixed-line-length-132"
    F90FLAGS="$F90FLAGS -ffree-line-length-0"
else # FC is ifort
    FFLAGS="$FFLAGS -132"
fi

# Request TAF write code with -f08
TAF_FORTRAN_VERS='F08'
# Extend free format to 150 columns and fixed format to 132 columns
USE_EXTENDED_SRC='t'
TAF_F90_FLAGS='-N 150'
