C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_cost_inloop_tl( mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use ihop_mod, only : free_ihop_ray2d
      use arr_mod, only : free_ihop_arrival

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1

C==============================================
C declare common blocks
C==============================================
      integer :: ihopobs_i_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_ind_glob(nfilesmax_ihop,nobsmax_ihop)
      integer :: ihopobs_ind_glob_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_j_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_k_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_sample1_ind(nfilesmax_ihop,nobsmax_ihop)
      integer :: ncidad(nfilesmax_ihop,nsx,nsy)
      integer :: ncidadglob(nfilesmax_ihop)
      integer :: nciddata(nfilesmax_ihop)
      integer :: ncidfwd(nfilesmax_ihop,nsx,nsy)
      integer :: ncidglob(nfilesmax_ihop)
      integer :: ncidtl(nfilesmax_ihop,nsx,nsy)
      integer :: ncidtlglob(nfilesmax_ihop)
      integer :: obsno(nfilesmax_ihop)
      integer :: obsno_tiled(nfilesmax_ihop,nsx,nsy)
      common /ihop_cost_i/ obsno, obsno_tiled, ihopobs_ind_glob, ihopobs_ind_glob_tiled, ncidfwd, ncidad, ncidtl, ncidglob, 
     $ncidadglob, ncidtlglob, nciddata, ihopobs_i_tiled, ihopobs_j_tiled, ihopobs_k_tiled, ihopobs_sample1_ind

      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

      double precision :: ihop_dummy(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy(nfilesmax_ihop)
      common /ihop_ctrl_dummy/ ihop_dummy, ihop_globaldummy

      double precision :: ihop_dummy_tl(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy_tl(nfilesmax_ihop)
      common /ihop_ctrl_dummy_tl/ ihop_dummy_tl, ihop_globaldummy_tl

      integer :: optimcycle
      common /optiparm_i/ optimcycle

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

      integer :: ikey_dynamics
      common /tamc_keys_i/ ikey_dynamics

C==============================================
C declare arguments
C==============================================
      integer :: myiter
      integer, intent(inout) :: mythid
      double precision, intent(in) :: mytime

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      double precision :: ihop_modval
      double precision :: ihop_modval_tl
      integer :: itdkey
      integer :: nobs
      integer :: num_file

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      itdkey = bi+(bj-1)*nsx+(ikey_dynamics-1)*nsx*nsy
      if (mythid == 1) then
        do bj = 1, nsy
          do bi = 1, nsx
            do num_file = 1, nfilesmax_ihop
              do nobs = 1, nobsmax_ihop
                if (nobs <= obsno_tiled(num_file,bi,bj)) then
                  if (ihopobs_time(num_file,nobs,bi,bj) >= mytime .and. ihopobs_time(num_file,nobs,bi,bj) < mytime+deltatclock) then
                    ihop_modval_tl = 0.d0
                    ihop_modval = 0
                    call ihop_cost_modval_tl( ihop_modval,ihop_modval_tl,num_file,1,1,mytime,mythid )
                    call g_active_write_ihop_tile( num_file,ihop_modval,ihop_modval_tl,nobs,optimcycle,bi,bj,mythid,ihop_dummy(
     $num_file,bi,bj),ihop_dummy_tl(num_file,bi,bj) )
                    PRINT *, "ESCOBAR inloop_tl", ihop_modval, ihop_modval_tl
                  endif
                endif
              end do
            end do
          end do
        end do
        if (mytime == endtime) then
          call free_ihop_ray2d( mythid )
          call free_ihop_arrival( mythid )
        endif
      endif

      end subroutine ihop_cost_inloop_tl

      subroutine ihop_cost_inloop( mytime, myiter, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use ihop_mod, only : free_ihop_ray2d
      use arr_mod, only : free_ihop_arrival

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nr = 15
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1

C==============================================
C declare common blocks
C==============================================
      integer :: ihopobs_i_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_ind_glob(nfilesmax_ihop,nobsmax_ihop)
      integer :: ihopobs_ind_glob_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_j_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_k_tiled(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      integer :: ihopobs_sample1_ind(nfilesmax_ihop,nobsmax_ihop)
      integer :: ncidad(nfilesmax_ihop,nsx,nsy)
      integer :: ncidadglob(nfilesmax_ihop)
      integer :: nciddata(nfilesmax_ihop)
      integer :: ncidfwd(nfilesmax_ihop,nsx,nsy)
      integer :: ncidglob(nfilesmax_ihop)
      integer :: ncidtl(nfilesmax_ihop,nsx,nsy)
      integer :: ncidtlglob(nfilesmax_ihop)
      integer :: obsno(nfilesmax_ihop)
      integer :: obsno_tiled(nfilesmax_ihop,nsx,nsy)
      common /ihop_cost_i/ obsno, obsno_tiled, ihopobs_ind_glob, ihopobs_ind_glob_tiled, ncidfwd, ncidad, ncidtl, ncidglob, 
     $ncidadglob, ncidtlglob, nciddata, ihopobs_i_tiled, ihopobs_j_tiled, ihopobs_k_tiled, ihopobs_sample1_ind

      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

      double precision :: ihop_dummy(nfilesmax_ihop,nsx,nsy)
      double precision :: ihop_globaldummy(nfilesmax_ihop)
      common /ihop_ctrl_dummy/ ihop_dummy, ihop_globaldummy

      integer :: optimcycle
      common /optiparm_i/ optimcycle

      double precision :: abeps
      double precision :: adjdumpfreq
      double precision :: adjmonitorfreq
      double precision :: affacmom
      double precision :: alph_ab
      double precision :: basetime
      double precision :: beta
      double precision :: beta_ab
      double precision :: bl79latvary
      double precision :: bottomdraglinear
      double precision :: bottomdragquadratic
      double precision :: cadjfreq
      double precision :: cffacmom
      double precision :: cg2dpcoffdfac
      double precision :: cg2dtargetresidual
      double precision :: cg2dtargetreswunit
      double precision :: cg3dtargetresidual
      double precision :: cg3dtargetreswunit
      double precision :: chkptfreq
      double precision :: convertfw2salt
      double precision :: cospower
      double precision :: dbdrref(nr)
      double precision :: delr(nr)
      double precision :: delrc(nr+1)
      double precision :: deltat
      double precision :: deltatclock
      double precision :: deltatfreesurf
      double precision :: deltatmom
      double precision :: diagfreq
      double precision :: diffk4s
      double precision :: diffk4t
      double precision :: diffkhs
      double precision :: diffkht
      double precision :: diffkr4s(nr)
      double precision :: diffkr4t(nr)
      double precision :: diffkrbl79deep
      double precision :: diffkrbl79ho
      double precision :: diffkrbl79scl
      double precision :: diffkrbl79surf
      double precision :: diffkrbleqdeep
      double precision :: diffkrbleqho
      double precision :: diffkrbleqscl
      double precision :: diffkrbleqsurf
      double precision :: diffkrnrs(nr)
      double precision :: diffkrnrt(nr)
      double precision :: drhosmall
      double precision :: dttracerlev(nr)
      double precision :: dumpfreq
      double precision :: endtime
      double precision :: epsab_cd
      double precision :: externforcingcycle
      double precision :: externforcingperiod
      double precision :: f0
      double precision :: fofacmom
      double precision :: fprime
      double precision :: freesurffac
      double precision :: gbaro
      double precision :: gravfacc(nr)
      double precision :: gravfacf(nr+1)
      double precision :: gravity
      double precision :: hfacinf
      double precision :: hfacmin
      double precision :: hfacmindp
      double precision :: hfacmindr
      double precision :: hfacmindz
      double precision :: hfacsup
      double precision :: hmixcriteria
      double precision :: hmixsmooth
      double precision :: implicdiv2dflow
      double precision :: implicitnhpress
      double precision :: implicsurfpress
      double precision :: ivdc_kappa
      double precision :: latbandclimrelax
      double precision :: mass2runit
      double precision :: monitorfreq
      double precision :: mtfacmom
      double precision :: nh_am2
      double precision :: omega
      double precision :: pcellmix_delr
      double precision :: pcellmix_diffkr(nr)
      double precision :: pcellmix_maxfac
      double precision :: pcellmix_viscar(nr)
      double precision :: pchkptfreq
      double precision :: pffacmom
      double precision :: phieuler
      double precision :: phiref(2*nr+1)
      double precision :: pref4eos(nr)
      double precision :: psieuler
      double precision :: radius_fromhorizgrid
      double precision :: rcd
      double precision :: recip_gravfacc(nr)
      double precision :: recip_gravfacf(nr+1)
      double precision :: recip_gravity
      double precision :: recip_rhoconst
      double precision :: recip_rhofacc(nr)
      double precision :: recip_rhofacf(nr+1)
      double precision :: recip_rsphere
      double precision :: rho1ref(nr)
      double precision :: rhoconst
      double precision :: rhoconstfresh
      double precision :: rhofacc(nr)
      double precision :: rhofacf(nr+1)
      double precision :: rhonil
      double precision :: rhoref(nr)
      double precision :: rotationperiod
      double precision :: rsigmabnd
      double precision :: rsphere
      double precision :: runit2mass
      double precision :: runit2z(nr)
      double precision :: rvel2wunit(nr+1)
      double precision :: salt_addmass
      double precision :: salt_evprrn
      double precision :: sealev_z
      double precision :: siceloadfac
      double precision :: sidedragfactor
      double precision :: smag3d_coeff
      double precision :: smag3d_diffcoeff
      double precision :: smoothabsfuncrange
      double precision :: sref(nr)
      double precision :: starttime
      double precision :: surf_pref
      double precision :: taucd
      double precision :: tausaltclimrelax
      double precision :: tauthetaclimrelax
      double precision :: tave_lastiter
      double precision :: tavefreq
      double precision :: tcylin
      double precision :: tcylout
      double precision :: temp_addmass
      double precision :: temp_evprrn
      double precision :: thetaconst
      double precision :: thetaeuler
      double precision :: top_pres
      double precision :: tref(nr)
      double precision :: vffacmom
      double precision :: visca4
      double precision :: visca4d
      double precision :: visca4grid
      double precision :: visca4gridmax
      double precision :: visca4gridmin
      double precision :: visca4max
      double precision :: visca4remax
      double precision :: visca4w
      double precision :: visca4z
      double precision :: viscah
      double precision :: viscahd
      double precision :: viscahgrid
      double precision :: viscahgridmax
      double precision :: viscahgridmin
      double precision :: viscahmax
      double precision :: viscahremax
      double precision :: viscahw
      double precision :: viscahz
      double precision :: viscarnr(nr)
      double precision :: viscc2leith
      double precision :: viscc2leithd
      double precision :: viscc2leithqg
      double precision :: viscc2smag
      double precision :: viscc4leith
      double precision :: viscc4leithd
      double precision :: viscc4smag
      double precision :: viscfacadj
      double precision :: wunit2rvel(nr+1)
      double precision :: xgorigin
      double precision :: ygorigin
      double precision :: z2runit(nr)
      double precision :: zroughbot
      common /parm_r/ cg2dtargetresidual, cg2dtargetreswunit, cg2dpcoffdfac, cg3dtargetresidual, cg3dtargetreswunit, delr, delrc, 
     $xgorigin, ygorigin, rsphere, recip_rsphere, radius_fromhorizgrid, sealev_z, top_pres, rsigmabnd, deltat, deltatmom, 
     $dttracerlev, deltatfreesurf, deltatclock, abeps, alph_ab, beta_ab, f0, beta, fprime, omega, rotationperiod, viscfacadj, 
     $viscah, viscahw, smag3d_coeff, smag3d_diffcoeff, viscahmax, viscahgrid, viscahgridmax, viscahgridmin, viscc2leith, 
     $viscc2leithd, viscc2leithqg, viscc2smag, viscc4smag, viscahd, viscahz, visca4d, visca4z, visca4, visca4w, visca4max, 
     $visca4grid, visca4gridmax, visca4gridmin, viscahremax, visca4remax, viscc4leith, viscc4leithd, viscarnr, diffkht, diffk4t, 
     $diffkrnrt, diffkr4t, diffkhs, diffk4s, diffkrnrs, diffkr4s, diffkrbl79surf, diffkrbl79deep, diffkrbl79scl, diffkrbl79ho, 
     $bl79latvary, diffkrbleqsurf, diffkrbleqdeep, diffkrbleqscl, diffkrbleqho, pcellmix_maxfac, pcellmix_delr, pcellmix_viscar, 
     $pcellmix_diffkr, taucd, rcd, epsab_cd, freesurffac, implicsurfpress, implicdiv2dflow, implicitnhpress, hfacmin, hfacmindz, 
     $hfacinf, hfacsup, gravity, recip_gravity, gbaro, gravfacc, recip_gravfacc, gravfacf, recip_gravfacf, rhonil, rhoconst, 
     $recip_rhoconst, rho1ref, rhofacc, recip_rhofacc, rhofacf, recip_rhofacf, rhoconstfresh, thetaconst, tref, sref, rhoref, 
     $dbdrref, surf_pref, pref4eos, phiref, rvel2wunit, wunit2rvel, runit2z, z2runit, mass2runit, runit2mass, basetime, starttime, 
     $endtime, chkptfreq, pchkptfreq, dumpfreq, adjdumpfreq, diagfreq, tavefreq, tave_lastiter, monitorfreq, adjmonitorfreq, 
     $affacmom, vffacmom, pffacmom, cffacmom, fofacmom, mtfacmom, cospower, cadjfreq, tauthetaclimrelax, tausaltclimrelax, 
     $latbandclimrelax, externforcingcycle, externforcingperiod, convertfw2salt, temp_evprrn, salt_evprrn, temp_addmass, 
     $salt_addmass, hfacmindr, hfacmindp, ivdc_kappa, hmixcriteria, drhosmall, hmixsmooth, sidedragfactor, bottomdraglinear, 
     $bottomdragquadratic, zroughbot, nh_am2, smoothabsfuncrange, siceloadfac, tcylin, tcylout, phieuler, thetaeuler, psieuler

      integer :: ikey_dynamics
      common /tamc_keys_i/ ikey_dynamics

C==============================================
C declare arguments
C==============================================
      integer :: myiter
      integer :: mythid
      double precision :: mytime

C==============================================
C declare local variables
C==============================================
      integer :: bi
      integer :: bj
      double precision :: ihop_modval
      integer :: itdkey
      integer :: nobs
      integer :: num_file

      itdkey = bi+(bj-1)*nsx+(ikey_dynamics-1)*nsx*nsy
      if (mythid == 1) then
        do bj = 1, nsy
          do bi = 1, nsx
            do num_file = 1, nfilesmax_ihop
              do nobs = 1, nobsmax_ihop
                if (nobs <= obsno_tiled(num_file,bi,bj)) then
                  if (ihopobs_time(num_file,nobs,bi,bj) >= mytime .and. ihopobs_time(num_file,nobs,bi,bj) < mytime+deltatclock) then
                    ihop_modval = 0
                    call ihop_cost_modval( ihop_modval,num_file,1,1,mytime,mythid )
                    call active_write_ihop_tile( num_file,ihop_modval,nobs,optimcycle,bi,bj,mythid,ihop_dummy(num_file,bi,bj) )
                  endif
                endif
              end do
            end do
          end do
        end do
        if (mytime == endtime) then
          call free_ihop_ray2d( mythid )
          call free_ihop_arrival( mythid )
        endif
      endif
      end subroutine ihop_cost_inloop
