C                           DISCLAIMER
C 
C   This file was generated by TAF version 6.8.11
C 
C   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
C   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
C   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
C   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
C   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
C   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
C   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
C   OF THE POSSIBILITY OF SUCH DAMAGES.
C 
C                           Haftungsbeschraenkung
C   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
C   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
C   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
C   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
C   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
C   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
C   Mitteilung darueber an FastOpt.
C 
      subroutine ihop_cost_modval_tl( modval, modval_tl, num_file, ri, rj, mytime, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use arr_mod, only : arr,narrival,nmaxarr
      use arr_mod, only : arr_tl
      use srpos_mod, only : pos
      use ihop_mod, only : rad2deg

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1

C==============================================
C declare common blocks
C==============================================
      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

      double precision :: geninfluence_tl(35604)
      double precision :: objf_ihop_tl(nfilesmax_ihop)
      common /ihop_cost_r_tl/ objf_ihop_tl, geninfluence_tl

C==============================================
C declare arguments
C==============================================
      double precision, intent(inout) :: modval
      double precision, intent(inout) :: modval_tl
      integer :: mythid
      double precision :: mytime
      integer :: num_file
      integer :: ri
      integer :: rj

C==============================================
C declare local variables
C==============================================
      integer :: ii

C----------------------------------------------
C TANGENT LINEAR AND FUNCTION STATEMENTS
C----------------------------------------------
      do ii = 1, 35604
        modval_tl = geninfluence_tl(ii)+modval_tl
        modval = modval+geninfluence(ii)
C        modval_tl = modval_tl+real(arr_tl(2,1,1)%delay_tl)
C        modval = modval+real(arr(2,1,1)%delay)
      end do
      print *, 'ESCOBAR modval _tl',modval, modval_tl

      end subroutine ihop_cost_modval_tl

      subroutine ihop_cost_modval( modval, num_file, ri, rj, mytime, mythid )
C******************************************************************
C******************************************************************
C** This routine was generated by Automatic differentiation.     **
C** FastOpt: Transformation of Algorithm in Fortran, TAF 6.8.11  **
C******************************************************************
C******************************************************************
C==============================================
C referencing used modules
C==============================================
      use arr_mod, only : arr,narrival,nmaxarr
      use srpos_mod, only : pos
      use ihop_mod, only : rad2deg

      implicit none

C==============================================
C declare parameters
C==============================================
      integer, parameter :: nfilesmax_ihop = 1
      integer, parameter :: nobsmax_ihop = 10
      integer, parameter :: nsx = 1
      integer, parameter :: nsy = 1

C==============================================
C declare common blocks
C==============================================
      double precision :: geninfluence(35604)
      double precision :: ihopobs_depth(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lat(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_lon(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_modmask
      double precision :: ihopobs_modmask_tiled(nsx,nsy)
      double precision :: ihopobs_time(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: ihopobs_uncert(nfilesmax_ihop,nobsmax_ihop,nsx,nsy)
      double precision :: mult_ihop(nfilesmax_ihop)
      double precision :: num_ihop(nfilesmax_ihop)
      double precision :: objf_ihop(nfilesmax_ihop)
      common /ihop_cost_r/ objf_ihop, num_ihop, mult_ihop, ihopobs_time, ihopobs_lat, ihopobs_lon, ihopobs_depth, ihopobs_uncert, 
     $ihopobs_modmask, ihopobs_modmask_tiled, geninfluence

C==============================================
C declare arguments
C==============================================
      double precision :: modval
      integer :: mythid
      double precision :: mytime
      integer :: num_file
      integer :: ri
      integer :: rj

C==============================================
C declare local variables
C==============================================
      integer :: ii

      do ii = 1, 35604
        modval = modval+geninfluence(ii)
C        modval = modval+real(arr(2,1,1)%delay)
      end do
      print *, 'ESCOBAR modval',modval
      end subroutine ihop_cost_modval
